//! Code emission: linted registry files → the generated module source.

use std::fmt::Write as _;

use crate::{
    COMMON_STATE, Chunk, ProcedureEntry, RegistryFile, SubjectEntry, camel, producer_module, snake,
};

/// CamelCase -> snake_case for generated constructor/builder fn names.
pub(crate) fn camel_to_snake(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

pub(crate) fn emit(files: &[RegistryFile], zk: &str) -> String {
    let mut out =
        String::from("// @generated by zenkey-build from the registry dir — do not edit.\n\n");
    for f in files {
        let module = producer_module(&f.name);
        let _ = writeln!(out, "pub mod {module} {{");
        let _ = writeln!(out, "    #[allow(unused_imports)]");
        let _ = writeln!(
            out,
            "    use {zk}::grammar::{{self, Class, KeyError, Origin, Producer}};\n    #[allow(unused_imports)]\n    use {zk}::key::{{Chunk, Key, Selector}};\n    #[allow(unused_imports)]\n    use {zk}::origin::{{ConcreteOrigin, HostOrigin, LocalOrigin}};\n    #[allow(unused_imports)]\n    use {zk}::selector::Scope;"
        );
        let _ = writeln!(out, "    #[allow(unused_imports)]");
        let _ = writeln!(out, "    use {zk}::qos::QosProfile;");
        let _ = writeln!(
            out,
            "\n    /// The raw registry slice — served verbatim by `introspect` (RFC 08 §6).\n    pub const REGISTRY_TOML: &str = include_str!({:?});\n",
            f.toml_path
        );
        if let Some(origin) = &f.service_origin {
            let _ = writeln!(
                out,
                "    /// This is a service registry: keys omit the producer chunk.\n    pub fn origin() -> Origin {{ Origin::service({origin:?}).expect(\"validated at build time\") }}\n"
            );
        } else {
            let _ = writeln!(
                out,
                "    pub fn producer() -> Producer {{ Producer::new({:?}).expect(\"validated at build time\") }}\n",
                f.name
            );
        }

        // Subject enum.
        let _ = writeln!(out, "    #[derive(Debug, Clone, PartialEq, Eq)]");
        let _ = writeln!(out, "    pub enum Subject {{");
        for s in &f.subjects {
            let mut fields = String::new();
            for c in &s.chunks {
                match c {
                    Chunk::Var(v) => {
                        let _ = write!(fields, "{}: Chunk, ", snake(v));
                    }
                    Chunk::Rest(v) => {
                        let _ = write!(fields, "{}: Vec<Chunk>, ", snake(v));
                    }
                    Chunk::Literal(_) => {}
                }
            }
            if fields.is_empty() {
                let _ = writeln!(out, "        {},", s.variant);
            } else {
                let _ = writeln!(out, "        {} {{ {}}},", s.variant, fields);
            }
        }
        let _ = writeln!(out, "    }}\n");

        // impl Subject.
        let _ = writeln!(out, "    impl Subject {{");

        // Slug-at-boundary constructors (RFC 08 §1.2): call sites pass raw
        // application values, the constructor slugs — `slug_key_chunk()` at
        // call sites is retired. `{host}` vars in service registries take a
        // typed HostId (H4).
        for s in &f.subjects {
            if s.chunks.iter().all(|c| matches!(c, Chunk::Literal(_))) {
                continue;
            }
            let fn_name = camel_to_snake(&s.variant);
            let mut args = String::new();
            let mut inits = String::new();
            for c in &s.chunks {
                match c {
                    Chunk::Var(v) => {
                        let n = snake(v);
                        if f.service_origin.is_some() && v == "host" {
                            let _ = write!(args, "{n}: &{zk}::origin::HostId, ");
                            let _ = write!(inits, "{n}: Chunk::from_valid({n}.as_str()), ");
                        } else {
                            let _ = write!(args, "{n}: impl AsRef<str>, ");
                            let _ = write!(inits, "{n}: Chunk::slug({n}), ");
                        }
                    }
                    Chunk::Rest(v) => {
                        let n = snake(v);
                        let _ = write!(args, "{n}: impl IntoIterator<Item = impl AsRef<str>>, ");
                        let _ = write!(inits, "{n}: {n}.into_iter().map(Chunk::slug).collect(), ");
                    }
                    Chunk::Literal(_) => {}
                }
            }
            let _ = writeln!(
                out,
                "        /// Construct [`Subject::{}`], slugging variables (RFC 03 §2).\n        pub fn {fn_name}({args}) -> Self {{ Self::{} {{ {inits}}} }}\n",
                s.variant, s.variant
            );
        }

        // class()
        let _ = writeln!(out, "        pub fn class(&self) -> Class {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let class = match s.class.as_str() {
                "telemetry" => "Class::Telemetry",
                "state" => "Class::State",
                _ => "Class::Events",
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {class},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // qos()
        let _ = writeln!(out, "        pub fn qos(&self) -> QosProfile {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let qos = match s.qos.as_str() {
                "sampled" => "QosProfile::Sampled",
                "refreshed" => "QosProfile::Refreshed",
                "transition" => "QosProfile::Transition",
                "alert" => "QosProfile::Alert",
                _ => "QosProfile::Frame",
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {qos},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // ttl_s()
        let _ = writeln!(out, "        pub fn ttl_s(&self) -> Option<u64> {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let ttl = match s.ttl_s {
                Some(t) => format!("Some({t})"),
                None => "None".to_string(),
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {ttl},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // rate() — events rate class (RFC 04 §1.3), None for other classes.
        let _ = writeln!(out, "        pub fn rate(&self) -> Option<&'static str> {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let rate = match &s.rate {
                Some(r) => format!("Some({r:?})"),
                None => "None".to_string(),
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {rate},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // payload_type() — the registry `type` column (RFC 08 §2). One payload
        // type per pattern (P5), so this is what a consumer decodes as.
        let _ = writeln!(
            out,
            "        /// The one payload type of every expansion of this subject (RFC 08 §2)."
        );
        let _ = writeln!(out, "        pub fn payload_type(&self) -> &'static str {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {:?},",
                s.variant, s.payload_type
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // unit() — RFC 08 §4: the registry is authoritative for units, whether
        // or not the key spells one as a suffix.
        let _ = writeln!(out, "        pub fn unit(&self) -> Option<&'static str> {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let unit = match &s.unit {
                Some(u) => format!("Some({u:?})"),
                None => "None".to_string(),
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {unit},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // encoding() — the declared payload framing (RFC 08 §2, v1.5).
        let _ = writeln!(
            out,
            "        /// The declared payload encoding, when the registry declares one\n        /// (resolution: sample `Encoding` > this > sniff; RFC 08 §7)."
        );
        let _ = writeln!(
            out,
            "        pub fn encoding(&self) -> Option<&'static str> {{"
        );
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let enc = match &s.encoding {
                Some(e) => format!("Some({e:?})"),
                None => "None".to_string(),
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {enc},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // cardinality() — the key-population bound the budget review enforces.
        let _ = writeln!(out, "        pub fn cardinality(&self) -> Option<u64> {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let c = match s.cardinality {
                Some(c) => format!("Some({c})"),
                None => "None".to_string(),
            };
            let _ = writeln!(out, "                Self::{} {{ .. }} => {c},", s.variant);
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // pattern()
        let _ = writeln!(out, "        pub fn pattern(&self) -> &'static str {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {:?},",
                s.variant, s.path
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // vars() — the variable bindings, in pattern order. A `{var...}` rest
        // binds as its chunks rejoined with `/`.
        let _ = writeln!(
            out,
            "        /// The pattern's variable bindings, in order (a `{{var...}}` rest rejoins with `/`)."
        );
        let _ = writeln!(
            out,
            "        pub fn vars(&self) -> Vec<(&'static str, String)> {{"
        );
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let mut binds = String::new();
            let mut body = String::from("vec![");
            for c in &s.chunks {
                match c {
                    Chunk::Literal(_) => {}
                    Chunk::Var(v) => {
                        let n = snake(v);
                        let _ = write!(binds, "{n}, ");
                        let _ = write!(body, "({v:?}, {n}.to_string()), ");
                    }
                    Chunk::Rest(v) => {
                        let n = snake(v);
                        let _ = write!(binds, "{n}, ");
                        let _ = write!(
                            body,
                            "({v:?}, {n}.iter().map(|c| c.as_str()).collect::<Vec<_>>().join(\"/\")), "
                        );
                    }
                }
            }
            body.push(']');
            let pat = if binds.is_empty() {
                format!("Self::{}", s.variant)
            } else {
                format!("Self::{} {{ {binds}}}", s.variant)
            };
            let _ = writeln!(out, "                {pat} => {body},");
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // parse(), precedence-ordered (RFC 08 §1: literal beats {var} beats
        // {var...}). Ordering is derived through `zenkey::pattern` — the same
        // primitive runtime tools match with — so generator and runtime can
        // never disagree (the parity test in fixture-tests pins it).
        let mut ordered: Vec<&SubjectEntry> = f.subjects.iter().collect();
        ordered.sort_by(|a, b| {
            let pa = zenkey::pattern::SubjectPattern::parse(&a.path).expect("linted");
            let pb = zenkey::pattern::SubjectPattern::parse(&b.path).expect("linted");
            pa.precedence().cmp(&pb.precedence())
        });
        let _ = writeln!(
            out,
            "        /// Refine a subject tail (chunks after the producer position).\n        pub fn parse(class: Class, tail: &[&str]) -> Option<Self> {{"
        );
        for s in &ordered {
            let class = match s.class.as_str() {
                "telemetry" => "Class::Telemetry",
                "state" => "Class::State",
                _ => "Class::Events",
            };
            let has_rest = matches!(s.chunks.last(), Some(Chunk::Rest(_)));
            let fixed = if has_rest {
                s.chunks.len() - 1
            } else {
                s.chunks.len()
            };
            let len_cond = if has_rest {
                if fixed == 0 {
                    "!tail.is_empty()".to_string()
                } else {
                    format!("tail.len() > {fixed}")
                }
            } else {
                format!("tail.len() == {fixed}")
            };
            let mut conds = vec![format!("class == {class}"), len_cond];
            for (i, c) in s.chunks.iter().enumerate() {
                if let Chunk::Literal(l) = c {
                    conds.push(format!("tail[{i}] == {l:?}"));
                }
            }
            let mut fields = String::new();
            for (i, c) in s.chunks.iter().enumerate() {
                match c {
                    Chunk::Var(v) => {
                        // Wire input is untrusted: an illegal chunk means "not
                        // a registered subject" (None), never a panic. `?` is
                        // sound as an early return — registry literals are
                        // valid chunks, so a tail holding an illegal chunk
                        // cannot match any other pattern either.
                        let _ = write!(fields, "{}: Chunk::parse(tail[{i}]).ok()?, ", snake(v));
                    }
                    Chunk::Rest(v) => {
                        let _ = write!(
                            fields,
                            "{}: tail[{i}..].iter().map(|c| Chunk::parse(c).ok()).collect::<Option<Vec<_>>>()?, ",
                            snake(v)
                        );
                    }
                    Chunk::Literal(_) => {}
                }
            }
            let construct = if fields.is_empty() {
                format!("Self::{}", s.variant)
            } else {
                format!("Self::{} {{ {fields}}}", s.variant)
            };
            let _ = writeln!(
                out,
                "            if {} {{ return Some({construct}); }}",
                conds.join(" && ")
            );
        }
        let _ = writeln!(out, "            None\n        }}\n");

        // parse_metric() — the ergonomic entry point. Consumers hold the
        // telemetry tail as one string (the telemetry metric name *is* the
        // subject tail, verbatim), so splitting it belongs here, once.
        let _ = writeln!(
            out,
            "        /// Refine a telemetry metric name (the subject tail as one `/`-joined string)."
        );
        let _ = writeln!(
            out,
            "        pub fn parse_metric(metric: &str) -> Option<Self> {{\n            // Stack buffer: no per-decode Vec for the common case (fixture\n            // max depth is 8; >16 chunks falls back to a heap collect).\n            let mut buf: [&str; 16] = [\"\"; 16];\n            let mut n = 0usize;\n            for c in metric.split('/') {{\n                if n == buf.len() {{\n                    let tail: Vec<&str> = metric.split('/').collect();\n                    return Self::parse(Class::Telemetry, &tail);\n                }}\n                buf[n] = c;\n                n += 1;\n            }}\n            Self::parse(Class::Telemetry, &buf[..n])\n        }}\n"
        );

        // family() — the fieldless mirror (RFC 08 §1.2).
        let _ = writeln!(
            out,
            "        /// This subject's family (the variant without its variables)."
        );
        let _ = writeln!(out, "        pub fn family(&self) -> Family {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => Family::{},",
                s.variant, s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}");
        let _ = writeln!(out, "    }}\n");

        // Family — consumer routing tables stop re-encoding the registry
        // (RFC 08 §1.2): fieldless ids with per-family selector builders.
        let _ = writeln!(
            out,
            "    /// Fieldless subject-family ids, with per-family selectors."
        );
        let _ = writeln!(
            out,
            "    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]"
        );
        let _ = writeln!(out, "    pub enum Family {{");
        for s in &f.subjects {
            let _ = writeln!(out, "        /// `{}` ({})", s.path, s.class);
            let _ = writeln!(out, "        {},", s.variant);
        }
        let _ = writeln!(out, "    }}\n");
        let _ = writeln!(out, "    impl Family {{");
        let _ = writeln!(out, "        pub const ALL: &[Family] = &[");
        for s in &f.subjects {
            let _ = writeln!(out, "            Family::{},", s.variant);
        }
        let _ = writeln!(out, "        ];\n");
        let _ = writeln!(out, "        pub fn class(self) -> Class {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let class = match s.class.as_str() {
                "telemetry" => "Class::Telemetry",
                "state" => "Class::State",
                _ => "Class::Events",
            };
            let _ = writeln!(out, "                Self::{} => {class},", s.variant);
        }
        let _ = writeln!(out, "            }}\n        }}\n");
        let _ = writeln!(out, "        pub fn pattern(self) -> &'static str {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let _ = writeln!(out, "                Self::{} => {:?},", s.variant, s.path);
        }
        let _ = writeln!(out, "            }}\n        }}\n");
        // selector(): {var} -> *, {var...} -> **, precomputed at build time.
        let selector_tail = |chunks: &[Chunk]| -> String {
            let parts: Vec<&str> = chunks
                .iter()
                .map(|c| match c {
                    Chunk::Literal(l) => l.as_str(),
                    Chunk::Var(_) => "*",
                    Chunk::Rest(_) => "**",
                })
                .collect();
            parts.join("/")
        };
        if let Some(origin) = &f.service_origin {
            let _ = writeln!(
                out,
                "        /// The family's selector (service origin is fixed; RFC 08 §1.2)."
            );
            let _ = writeln!(out, "        pub fn selector(self) -> Selector {{");
            let _ = writeln!(out, "            match self {{");
            for s in &f.subjects {
                let class = &s.class;
                let tail = selector_tail(&s.chunks);
                let sel = format!("v1/{origin}/{class}/{tail}");
                let _ = writeln!(
                    out,
                    "                Self::{} => Selector::from_canonical({sel:?}.to_string()),",
                    s.variant
                );
            }
            let _ = writeln!(out, "            }}\n        }}");
        } else {
            let _ = writeln!(
                out,
                "        /// The family's selector in a scope: `{{var}}` -> `*`, `{{var...}}` -> `**` (RFC 08 §1.2)."
            );
            let _ = writeln!(
                out,
                "        pub fn selector(self, scope: Scope) -> Selector {{"
            );
            let _ = writeln!(out, "            match self {{");
            for s in &f.subjects {
                let class = &s.class;
                let tail = selector_tail(&s.chunks);
                let suffix = format!("/{class}/{}/{tail}", f.name);
                let _ = writeln!(
                    out,
                    "                Self::{} => Selector::from_canonical(format!(\"v1/{{}}{suffix}\", scope.chunk())),",
                    s.variant
                );
            }
            let _ = writeln!(out, "            }}\n        }}");
        }
        let _ = writeln!(out, "    }}\n");

        // Full-key builders: single-pass, infallible (fields are validated
        // Chunks; class/producer are registry constants). Publishing takes
        // the typed LocalOrigin (G5); addressing takes any host origin.
        let emit_subject_arms = |out: &mut String, subjects: &[SubjectEntry]| {
            for s in subjects {
                let mut binds = String::new();
                let mut body = String::new();
                let mut pending = String::new();
                let state_guard = s.class == "state";
                for c in &s.chunks {
                    match c {
                        Chunk::Literal(l) => {
                            pending.push('/');
                            pending.push_str(l);
                        }
                        Chunk::Var(v) => {
                            let n = snake(v);
                            let _ = write!(binds, "{n}, ");
                            pending.push('/');
                            if pending == "/" {
                                let _ = write!(body, "k.push('/'); ");
                            } else {
                                let _ = write!(body, "k.push_str({pending:?}); ");
                            }
                            pending.clear();
                            if state_guard {
                                let _ = write!(
                                    body,
                                    "assert!({n}.as_str() != \"alive\", \"reserved `alive` leaf (RFC 03 §3)\"); "
                                );
                            }
                            let _ = write!(body, "k.push_str({n}); ");
                        }
                        Chunk::Rest(v) => {
                            let n = snake(v);
                            let _ = write!(binds, "{n}, ");
                            if pending == "/" {
                                let _ = write!(body, "k.push('/'); ");
                                pending.clear();
                            } else if !pending.is_empty() {
                                let _ = write!(body, "k.push_str({pending:?}); ");
                                pending.clear();
                            }
                            if state_guard {
                                let _ = write!(
                                    body,
                                    "for c in {n} {{ assert!(c.as_str() != \"alive\", \"reserved `alive` leaf (RFC 03 §3)\"); k.push('/'); k.push_str(c); }} "
                                );
                            } else {
                                let _ =
                                    write!(body, "for c in {n} {{ k.push('/'); k.push_str(c); }} ");
                            }
                        }
                    }
                }
                if !pending.is_empty() {
                    let _ = write!(body, "k.push_str({pending:?}); ");
                }
                let pat = if binds.is_empty() {
                    format!("Subject::{}", s.variant)
                } else {
                    format!("Subject::{} {{ {binds}}}", s.variant)
                };
                let _ = writeln!(out, "            {pat} => {{ {body}}}");
            }
        };
        if let Some(origin) = &f.service_origin {
            let _ = writeln!(
                out,
                "    /// Base-relative data key for this service's subject (origin is fixed).\n    pub fn key(subject: &Subject) -> Key {{"
            );
            let _ = writeln!(
                out,
                "        let mut k = String::with_capacity(96);\n        k.push_str(\"v1/{origin}/\");\n        k.push_str(subject.class().chunk());\n        match subject {{"
            );
            emit_subject_arms(&mut out, &f.subjects);
            let _ = writeln!(out, "        }}\n        Key::from_canonical(k)\n    }}");
        } else {
            let _ = writeln!(
                out,
                "    /// Base-relative data key, published under this process's own origin\n    /// (RFC 08 §1.1/G5: publishing is Local by type).\n    pub fn key(o: &LocalOrigin, subject: &Subject) -> Key {{\n        key_impl(o.chunk(), {:?}, subject)\n    }}\n\n    /// Address one specific host's document (drill-down GETs, exact subscriptions).\n    pub fn key_at(o: &impl HostOrigin, subject: &Subject) -> Key {{\n        key_impl(o.chunk(), {:?}, subject)\n    }}\n\n    /// As [`key`], for an instance-suffixed producer (RFC 03 §1.5).\n    pub fn key_as(o: &LocalOrigin, producer: &Producer, subject: &Subject) -> Key {{\n        key_impl(o.chunk(), &producer.chunk(), subject)\n    }}",
                f.name, f.name
            );
            let _ = writeln!(
                out,
                "\n    fn key_impl(origin: &str, producer: &str, subject: &Subject) -> Key {{\n        let mut k = String::with_capacity(96);\n        k.push_str(\"v1/\");\n        k.push_str(origin);\n        k.push('/');\n        k.push_str(subject.class().chunk());\n        k.push('/');\n        k.push_str(producer);\n        match subject {{"
            );
            emit_subject_arms(&mut out, &f.subjects);
            let _ = writeln!(out, "        }}\n        Key::from_canonical(k)\n    }}");
        }

        // Procedures.
        if !f.procedures.is_empty() {
            let _ = writeln!(out, "\n    #[derive(Debug, Clone, Copy, PartialEq, Eq)]");
            let _ = writeln!(out, "    pub enum ProcedureId {{");
            for p in &f.procedures {
                let _ = writeln!(out, "        /// `{}` ({})", p.path, p.kind);
                let _ = writeln!(out, "        {},", p.variant);
            }
            let _ = writeln!(out, "    }}\n");
            let _ = writeln!(out, "    impl ProcedureId {{");
            let _ = writeln!(out, "        pub const ALL: &[ProcedureId] = &[");
            for p in &f.procedures {
                let _ = writeln!(out, "            ProcedureId::{},", p.variant);
            }
            let _ = writeln!(out, "        ];\n");
            let _ = writeln!(
                out,
                "        pub fn chunks(self) -> &'static [&'static str] {{"
            );
            let _ = writeln!(out, "            match self {{");
            for p in &f.procedures {
                let list: Vec<String> = p
                    .chunks
                    .iter()
                    .map(|c| match c {
                        Chunk::Literal(l) => format!("{l:?}"),
                        Chunk::Var(v) | Chunk::Rest(v) => format!("{:?}", format!("{{{v}}}")),
                    })
                    .collect();
                let _ = writeln!(
                    out,
                    "                Self::{} => &[{}],",
                    p.variant,
                    list.join(", ")
                );
            }
            let _ = writeln!(out, "            }}\n        }}\n");
            let _ = writeln!(out, "        pub fn kind(self) -> &'static str {{");
            let _ = writeln!(out, "            match self {{");
            for p in &f.procedures {
                let _ = writeln!(out, "                Self::{} => {:?},", p.variant, p.kind);
            }
            let _ = writeln!(out, "            }}\n        }}\n");
            let _ = writeln!(
                out,
                "        /// The registered path, e.g. `artifact/request`."
            );
            let _ = writeln!(out, "        pub fn path(self) -> &'static str {{");
            let _ = writeln!(out, "            match self {{");
            for p in &f.procedures {
                let _ = writeln!(out, "                Self::{} => {:?},", p.variant, p.path);
            }
            let _ = writeln!(out, "            }}\n        }}\n");
            // request_type()/reply_type() — RFC 08 §2. A `read` has no request
            // body; a write that acks with nothing has no reply type.
            for (method, field) in [
                ("request_type", &|p: &ProcedureEntry| {
                    p.request.clone() as Option<String>
                }),
                ("reply_type", &|p: &ProcedureEntry| {
                    p.reply.clone() as Option<String>
                }),
            ]
                as [(&str, &dyn Fn(&ProcedureEntry) -> Option<String>); 2]
            {
                let _ = writeln!(
                    out,
                    "        pub fn {method}(self) -> Option<&'static str> {{"
                );
                let _ = writeln!(out, "            match self {{");
                for p in &f.procedures {
                    let t = match field(p) {
                        Some(t) => format!("Some({t:?})"),
                        None => "None".to_string(),
                    };
                    let _ = writeln!(out, "                Self::{} => {t},", p.variant);
                }
                let _ = writeln!(out, "            }}\n        }}\n");
            }
            // fanout()/idempotent() (RFC 08 §2, parsed since v1.5 — #9).
            let _ = writeln!(
                out,
                "        /// May a `*`-origin fan-out call target this procedure? (RFC 08 §2, G2)"
            );
            let _ = writeln!(out, "        pub fn fanout_allowed(self) -> bool {{");
            let _ = writeln!(out, "            match self {{");
            for p in &f.procedures {
                let v = matches!(p.fanout, crate::Fanout::Allowed);
                let _ = writeln!(out, "                Self::{} => {v},", p.variant);
            }
            let _ = writeln!(out, "            }}\n        }}\n");
            let _ = writeln!(
                out,
                "        /// Whether a retried call is safe (RFC 05 §3)."
            );
            let _ = writeln!(out, "        pub fn idempotent(self) -> bool {{");
            let _ = writeln!(out, "            match self {{");
            for p in &f.procedures {
                let _ = writeln!(
                    out,
                    "                Self::{} => {},",
                    p.variant, p.idempotent
                );
            }
            let _ = writeln!(out, "            }}\n        }}\n");
            let _ = writeln!(
                out,
                "        /// The declared request/reply encoding, when declared (RFC 08 §2, v1.5)."
            );
            let _ = writeln!(
                out,
                "        pub fn encoding(self) -> Option<&'static str> {{"
            );
            let _ = writeln!(out, "            match self {{");
            for p in &f.procedures {
                let enc = match &p.encoding {
                    Some(e) => format!("Some({e:?})"),
                    None => "None".to_string(),
                };
                let _ = writeln!(out, "                Self::{} => {enc},", p.variant);
            }
            let _ = writeln!(out, "            }}\n        }}\n");
            let _ = writeln!(out, "    }}\n");

            // FleetProcedureId — the fanout-allowed subset. A forbidden-fanout
            // write has NO fleet spelling anywhere in this module (G2 as a
            // type-level fact). Service registries skip it: `*` never matches
            // a verbatim service origin (D4).
            let allowed: Vec<&ProcedureEntry> = f
                .procedures
                .iter()
                .filter(|p| matches!(p.fanout, crate::Fanout::Allowed))
                .collect();
            if f.service_origin.is_none() && !allowed.is_empty() {
                let _ = writeln!(
                    out,
                    "    /// The fanout-allowed subset of [`ProcedureId`] (RFC 08 §2, G2):\n    /// fleet selectors exist only for these — a forbidden-fanout write is\n    /// unspellable."
                );
                let _ = writeln!(out, "    #[derive(Debug, Clone, Copy, PartialEq, Eq)]");
                let _ = writeln!(out, "    pub enum FleetProcedureId {{");
                for p in &allowed {
                    let _ = writeln!(out, "        /// `{}` ({})", p.path, p.kind);
                    let _ = writeln!(out, "        {},", p.variant);
                }
                let _ = writeln!(out, "    }}\n");
                let _ = writeln!(out, "    impl FleetProcedureId {{");
                let _ = writeln!(out, "        pub const ALL: &[FleetProcedureId] = &[");
                for p in &allowed {
                    let _ = writeln!(out, "            FleetProcedureId::{},", p.variant);
                }
                let _ = writeln!(out, "        ];\n    }}\n");
                let _ = writeln!(
                    out,
                    "    impl From<FleetProcedureId> for ProcedureId {{\n        fn from(p: FleetProcedureId) -> ProcedureId {{\n            match p {{"
                );
                for p in &allowed {
                    let _ = writeln!(
                        out,
                        "                FleetProcedureId::{} => ProcedureId::{},",
                        p.variant, p.variant
                    );
                }
                let _ = writeln!(out, "            }}\n        }}\n    }}\n");
                let _ = writeln!(
                    out,
                    "    /// Fleet fan-in selector: `v1/*/@rpc/{}/<path>` with `{{var}}` -> `*`.\n    /// Callers MUST use query target `All` (RFC 05 §2.1).\n    pub fn rpc_fleet_selector(p: FleetProcedureId) -> Selector {{\n        match p {{",
                    f.name
                );
                for p in &allowed {
                    let tail: Vec<&str> = p
                        .chunks
                        .iter()
                        .map(|c| match c {
                            Chunk::Literal(l) => l.as_str(),
                            _ => "*",
                        })
                        .collect();
                    let sel = format!("v1/*/@rpc/{}/{}", f.name, tail.join("/"));
                    let _ = writeln!(
                        out,
                        "            FleetProcedureId::{} => Selector::from_canonical({sel:?}.to_string()),",
                        p.variant
                    );
                }
                let _ = writeln!(out, "        }}\n    }}\n");
            }

            if f.service_origin.is_some() {
                let _ = writeln!(
                    out,
                    "    /// Base-relative `@rpc` key for this service's procedure (origin fixed).\n    /// Errs on a `{{var}}`-bearing pattern — use the named per-procedure builder.\n    pub fn rpc_key(p: ProcedureId) -> Result<Key, KeyError> {{\n        if p.chunks().iter().any(|c| c.starts_with('{{')) {{\n            return Err(KeyError::Parse(format!(\"procedure {{}} has variables; use its named builder\", p.path())));\n        }}\n        grammar::rpc_key(&origin(), None, p.chunks())\n    }}\n\n    /// The serve-side selector: every `{{var}}` becomes `*`.\n    pub fn rpc_serve_key(p: ProcedureId) -> Selector {{\n        let mut key = format!(\"{{}}/{{}}/{{}}\", grammar::VERSION_CHUNK, origin().chunk(), grammar::PLANE_RPC);\n        for c in p.chunks() {{\n            key.push('/');\n            key.push_str(if c.starts_with('{{') {{ \"*\" }} else {{ c }});\n        }}\n        Selector::from_canonical(key)\n    }}"
                );
            } else {
                let _ = writeln!(
                    out,
                    "    /// Base-relative `@rpc` key for this producer's procedure at one host\n    /// (RFC 08 §1.1: the origin is typed and concrete — never a fleet).\n    /// Errs on a `{{var}}`-bearing pattern — use the named per-procedure builder.\n    pub fn rpc_key(o: &impl HostOrigin, p: ProcedureId) -> Result<Key, KeyError> {{\n        if p.chunks().iter().any(|c| c.starts_with('{{')) {{\n            return Err(KeyError::Parse(format!(\"procedure {{}} has variables; use its named builder\", p.path())));\n        }}\n        grammar::rpc_key(&o.to_origin(), Some(&producer()), p.chunks())\n    }}\n\n    /// The serve-side selector (this process's own queryable): every\n    /// `{{var}}` becomes `*`.\n    pub fn rpc_serve_key(o: &LocalOrigin, p: ProcedureId) -> Selector {{\n        let mut key = format!(\"{{}}/{{}}/{{}}/{{}}\", grammar::VERSION_CHUNK, o.chunk(), grammar::PLANE_RPC, producer().chunk());\n        for c in p.chunks() {{\n            key.push('/');\n            key.push_str(if c.starts_with('{{') {{ \"*\" }} else {{ c }});\n        }}\n        Selector::from_canonical(key)\n    }}"
                );
            }

            // Named-arg per-procedure builders (G6: the actuated resource is
            // a typed path argument, slugged at the boundary).
            for p in &f.procedures {
                let fn_base = camel_to_snake(&p.variant);
                let mut args = String::new();
                let mut body = String::new();
                let mut pending = String::new();
                for c in &p.chunks {
                    match c {
                        Chunk::Literal(l) => {
                            pending.push('/');
                            pending.push_str(l);
                        }
                        Chunk::Var(v) => {
                            let n = snake(v);
                            let _ = write!(args, "{n}: impl AsRef<str>, ");
                            pending.push('/');
                            if pending == "/" {
                                let _ = write!(body, "k.push('/'); ");
                            } else {
                                let _ = write!(body, "k.push_str({pending:?}); ");
                            }
                            pending.clear();
                            let _ = write!(body, "k.push_str(&Chunk::slug({n})); ");
                        }
                        Chunk::Rest(_) => unreachable!("linted: no rest in procedures"),
                    }
                }
                if !pending.is_empty() {
                    let _ = write!(body, "k.push_str({pending:?}); ");
                }
                if f.service_origin.is_some() {
                    let origin = f.service_origin.as_deref().unwrap();
                    let _ = writeln!(
                        out,
                        "    /// Call key for `{}` (origin fixed; args slugged, RFC 03 §2).\n    pub fn {fn_base}_key({args}) -> Key {{\n        let mut k = String::with_capacity(96);\n        k.push_str(\"v1/{origin}/@rpc\");\n        {body}\n        Key::from_canonical(k)\n    }}\n",
                        p.path
                    );
                } else {
                    let _ = writeln!(
                        out,
                        "    /// Call key for `{}` at one host (typed origin, G5; args slugged).\n    pub fn {fn_base}_key(o: &impl HostOrigin, {args}) -> Key {{\n        let mut k = String::with_capacity(96);\n        k.push_str(\"v1/\");\n        k.push_str(o.chunk());\n        k.push_str(\"/@rpc/{}\");\n        {body}\n        Key::from_canonical(k)\n    }}\n",
                        p.path, f.name
                    );
                }
            }
        }

        // Media plane (RFC 07 §1, RFC 08 §2 — H2 delivers the v1.3 promise).
        // Deliberately NO wildcard/Family-style selector: a viewer subscribes
        // to exactly one tier (the v1.3 tier-wildcard revocation).
        if !f.media.is_empty() && f.service_origin.is_none() {
            let _ = writeln!(
                out,
                "    /// Media-plane subjects (RFC 07 §1). No wildcard selector on purpose."
            );
            let _ = writeln!(out, "    #[derive(Debug, Clone, PartialEq, Eq)]");
            let _ = writeln!(out, "    pub enum Media {{");
            for m in &f.media {
                let mut fields = String::new();
                for c in &m.chunks {
                    if let Chunk::Var(v) = c {
                        let _ = write!(fields, "{}: Chunk, ", snake(v));
                    }
                }
                let _ = writeln!(out, "        /// `{}` ({})", m.path, m.encoding);
                if fields.is_empty() {
                    let _ = writeln!(out, "        {},", m.variant);
                } else {
                    let _ = writeln!(out, "        {} {{ {}}},", m.variant, fields);
                }
            }
            let _ = writeln!(out, "    }}\n");
            let _ = writeln!(out, "    impl Media {{");
            for m in &f.media {
                if m.chunks.iter().all(|c| matches!(c, Chunk::Literal(_))) {
                    continue;
                }
                let fn_name = camel_to_snake(&m.variant);
                let mut args = String::new();
                let mut inits = String::new();
                for c in &m.chunks {
                    if let Chunk::Var(v) = c {
                        let n = snake(v);
                        let _ = write!(args, "{n}: impl AsRef<str>, ");
                        let _ = write!(inits, "{n}: Chunk::slug({n}), ");
                    }
                }
                let _ = writeln!(
                    out,
                    "        /// Construct [`Media::{}`], slugging variables (RFC 03 §2).\n        pub fn {fn_name}({args}) -> Self {{ Self::{} {{ {inits}}} }}\n",
                    m.variant, m.variant
                );
            }
            for (method, get) in [
                (
                    "encoding",
                    &(|m: &crate::MediaEntry| m.encoding.clone())
                        as &dyn Fn(&crate::MediaEntry) -> String,
                ),
                ("attachment_type", &|m: &crate::MediaEntry| {
                    m.attachment.clone()
                }),
                ("pattern", &|m: &crate::MediaEntry| m.path.clone()),
            ] {
                let doc = match method {
                    "encoding" => "The wire `Encoding` declared for every sample (RFC 08 §2).",
                    "attachment_type" => "The per-frame attachment sidecar type (RFC 08 §2).",
                    _ => "The registered path pattern.",
                };
                let _ = writeln!(out, "        /// {doc}");
                let _ = writeln!(
                    out,
                    "        pub fn {method}(&self) -> &'static str {{\n            match self {{"
                );
                for m in &f.media {
                    let _ = writeln!(
                        out,
                        "                Self::{} {{ .. }} => {:?},",
                        m.variant,
                        get(m)
                    );
                }
                let _ = writeln!(out, "            }}\n        }}\n");
            }
            let _ = writeln!(out, "        pub fn cardinality(&self) -> Option<u64> {{");
            let _ = writeln!(out, "            match self {{");
            for m in &f.media {
                let c = match m.cardinality {
                    Some(c) => format!("Some({c})"),
                    None => "None".to_string(),
                };
                let _ = writeln!(out, "                Self::{} {{ .. }} => {c},", m.variant);
            }
            let _ = writeln!(out, "            }}\n        }}\n    }}\n");
            // Builders: publish under the local origin; view one host's
            // stream by exact key (RemoteOrigin — never a wildcard).
            let emit_media_impl = |out: &mut String, f: &RegistryFile| {
                let _ = writeln!(
                    out,
                    "    fn media_key_impl(origin: &str, m: &Media) -> Key {{\n        let mut k = String::with_capacity(96);\n        k.push_str(\"v1/\");\n        k.push_str(origin);\n        k.push_str(\"/@media/{}\");\n        match m {{",
                    f.name
                );
                for m in &f.media {
                    let mut binds = String::new();
                    let mut body = String::new();
                    let mut pending = String::new();
                    for c in &m.chunks {
                        match c {
                            Chunk::Literal(l) => {
                                pending.push('/');
                                pending.push_str(l);
                            }
                            Chunk::Var(v) => {
                                let n = snake(v);
                                let _ = write!(binds, "{n}, ");
                                pending.push('/');
                                if pending == "/" {
                                    let _ = write!(body, "k.push('/'); ");
                                } else {
                                    let _ = write!(body, "k.push_str({pending:?}); ");
                                }
                                pending.clear();
                                let _ = write!(body, "k.push_str({n}); ");
                            }
                            Chunk::Rest(_) => unreachable!("linted: no rest in media"),
                        }
                    }
                    if !pending.is_empty() {
                        let _ = write!(body, "k.push_str({pending:?}); ");
                    }
                    let pat = if binds.is_empty() {
                        format!("Media::{}", m.variant)
                    } else {
                        format!("Media::{} {{ {binds}}}", m.variant)
                    };
                    let _ = writeln!(out, "            {pat} => {{ {body}}}");
                }
                let _ = writeln!(out, "        }}\n        Key::from_canonical(k)\n    }}");
            };
            let _ = writeln!(
                out,
                "    /// Publish key for a media subject under this process's own origin.\n    pub fn media_key(o: &LocalOrigin, m: &Media) -> Key {{\n        media_key_impl(o.chunk(), m)\n    }}\n\n    /// One host's media key, exact (RFC 07 §3: viewers never wildcard a\n    /// chunk the catalogue publishes).\n    pub fn media_key_at(o: &{zk}::origin::RemoteOrigin, m: &Media) -> Key {{\n        media_key_impl(ConcreteOrigin::chunk(o), m)\n    }}"
            );
            emit_media_impl(&mut out, f);
        }

        let _ = writeln!(out, "}}\n");
    }

    // Raw registry slice by producer name (introspect, RFC 08 §6).
    let _ = writeln!(
        out,
        "/// The raw registry slice for a producer/service, by base name."
    );
    let _ = writeln!(
        out,
        "pub fn registry_toml(name: &str) -> Option<&'static str> {{"
    );
    let _ = writeln!(out, "    match name {{");
    for f in files {
        let module = producer_module(&f.name);
        let _ = writeln!(
            out,
            "        {:?} => Some({module}::REGISTRY_TOML),",
            f.name
        );
    }
    let _ = writeln!(out, "        _ => None,\n    }}\n}}\n");

    // Every registry slice this build was compiled against, by base name. A
    // fleet-capabilities view fans `introspect` out over exactly this list and
    // diffs each reply against the local slice.
    let _ = writeln!(
        out,
        "/// Every producer/service this build knows, with its raw registry slice."
    );
    let _ = writeln!(out, "pub const REGISTRIES: &[(&str, &str)] = &[");
    for f in files {
        let module = producer_module(&f.name);
        let _ = writeln!(out, "    ({:?}, {module}::REGISTRY_TOML),", f.name);
    }
    let _ = writeln!(out, "];\n");

    // Cross-producer dispatch: refine a structural key into (producer, subject).
    let _ = writeln!(out, "/// Refined subject from any registered producer.");
    let _ = writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]");
    let _ = writeln!(out, "pub enum AnySubject {{");
    for f in files {
        let module = producer_module(&f.name);
        let _ = writeln!(out, "    {}({module}::Subject),", camel(&[f.name.as_str()]));
    }
    let _ = writeln!(out, "}}\n");

    // AnySubject accessors: producer-agnostic introspection of a refined
    // subject. `vars()` is what lets a consumer read `{iface}` by name instead
    // of by position.
    let _ = writeln!(out, "impl AnySubject {{");
    for (method, ret, body) in [
        ("producer_name", "&'static str".to_string(), "NAME"),
        ("class", format!("{zk}::grammar::Class"), "s.class()"),
        ("pattern", "&'static str".to_string(), "s.pattern()"),
        (
            "vars",
            "Vec<(&'static str, String)>".to_string(),
            "s.vars()",
        ),
        (
            "payload_type",
            "&'static str".to_string(),
            "s.payload_type()",
        ),
        ("unit", "Option<&'static str>".to_string(), "s.unit()"),
        ("cardinality", "Option<u64>".to_string(), "s.cardinality()"),
        ("qos", format!("{zk}::qos::QosProfile"), "s.qos()"),
        ("ttl_s", "Option<u64>".to_string(), "s.ttl_s()"),
        ("rate", "Option<&'static str>".to_string(), "s.rate()"),
    ] {
        let _ = writeln!(out, "    pub fn {method}(&self) -> {ret} {{");
        let _ = writeln!(out, "        match self {{");
        for f in files {
            let variant = camel(&[f.name.as_str()]);
            let arm = if body == "NAME" {
                format!("{:?}", f.name)
            } else {
                body.to_string()
            };
            let bind = if body == "NAME" { "_" } else { "s" };
            let _ = writeln!(out, "            Self::{variant}({bind}) => {arm},");
        }
        let _ = writeln!(out, "        }}\n    }}\n");
    }
    let _ = writeln!(out, "}}\n");

    // AnySubject::common_state() — refine any producer's state subject into
    // the RFC-defined framework set. Driven by the `common = "..."` field on
    // registry entries, so it cannot drift from the registry: drop the field
    // (or the subject) and its arm disappears here.
    let _ = writeln!(out, "impl AnySubject {{");
    let _ = writeln!(
        out,
        "    /// The framework state subject this refines to, if any.\n    pub fn common_state(&self) -> Option<{zk}::common_state::CommonState<'_>> {{\n        use {zk}::common_state::CommonState as C;\n        match self {{"
    );
    for f in files {
        let module = producer_module(&f.name);
        let variant = camel(&[f.name.as_str()]);
        let _ = writeln!(out, "            Self::{variant}(s) => match s {{");
        let mut mapped = 0usize;
        for s in &f.subjects {
            let Some(common) = &s.common else { continue };
            let (_, ctor, _) = COMMON_STATE
                .iter()
                .find(|(n, _, _)| n == common)
                .expect("common name validated at load time");
            mapped += 1;
            // Bind the pattern's variables by name; the CommonState ctor uses
            // the same names (linted at load time), so field-init shorthand
            // lines them up.
            let binds: Vec<String> = s
                .chunks
                .iter()
                .filter_map(|c| match c {
                    Chunk::Var(v) | Chunk::Rest(v) => Some(snake(v)),
                    Chunk::Literal(_) => None,
                })
                .collect();
            let pat = if binds.is_empty() {
                format!("{module}::Subject::{}", s.variant)
            } else {
                format!(
                    "{module}::Subject::{} {{ {} }}",
                    s.variant,
                    binds.join(", ")
                )
            };
            let _ = writeln!(out, "                {pat} => Some(C::{ctor}),");
        }
        // A producer whose every subject is a framework one (an `@catalog`
        // service) leaves nothing for a wildcard arm to catch.
        if mapped < f.subjects.len() {
            let _ = writeln!(out, "                _ => None,");
        }
        let _ = writeln!(out, "            }},");
    }
    let _ = writeln!(out, "        }}\n    }}\n}}\n");

    let _ = writeln!(
        out,
        "/// Registry-refine a structurally parsed key (RFC 08 §1 parse direction).\n/// `producer_name` is the *base* name (instance suffix already stripped by\n/// `Producer::parse_chunk`); service keys pass the service\n/// name (e.g. \"catalog\").\npub fn parse_subject(producer_name: &str, class: {zk}::grammar::Class, tail: &[&str]) -> Option<AnySubject> {{"
    );
    let _ = writeln!(out, "    match producer_name {{");
    for f in files {
        let module = producer_module(&f.name);
        let _ = writeln!(
            out,
            "        {:?} => {module}::Subject::parse(class, tail).map(AnySubject::{}),",
            f.name,
            camel(&[f.name.as_str()])
        );
    }
    let _ = writeln!(out, "        _ => None,\n    }}\n}}\n");

    // Refined + refine_key/refine_full_key (RFC 08 §1 parse direction,
    // generated since v1.5 — deletes the hand-written copies consumers kept).
    let _ = writeln!(
        out,
        "/// A wire key refined against this build's registries.\n#[derive(Debug, Clone, PartialEq, Eq)]\npub struct Refined<'k> {{\n    pub key: {zk}::grammar::StructuralKey<'k>,\n    /// Producer (or service) base name.\n    pub producer: &'static str,\n    pub subject: AnySubject,\n}}\n"
    );
    let _ = writeln!(
        out,
        "/// Refine a base-relative wire key into its registered subject.\npub fn refine_key(key: &str) -> Option<Refined<'_>> {{\n    let parsed = {zk}::grammar::parse(key).ok()?;\n    let {zk}::grammar::ClassOrPlane::Class(class) = parsed.class else {{ return None; }};\n    let name: &str = match (&parsed.producer, &parsed.origin) {{\n        (Some(p), _) => p.name(),\n        (None, {zk}::grammar::Origin::Service(s)) => s.trim_start_matches('@'),\n        _ => return None,\n    }};\n    let subject = parse_subject(name, class, &parsed.subject)?;\n    let producer = subject.producer_name();\n    Some(Refined {{ key: parsed, producer, subject }})\n}}\n"
    );
    let _ = writeln!(
        out,
        "/// As [`refine_key`], for a full wire key seen by an un-namespaced\n/// observer (strips `base` first; RFC 09 §5).\npub fn refine_full_key<'k>(base: &str, key: &'k str) -> Option<Refined<'k>> {{\n    refine_key({zk}::grammar::strip_base(base, key)?)\n}}\n"
    );

    // TYPE_NAMES + zenkey_for_each_payload_type! — the type table as data
    // and as a macro (RFC 08 §5/§7).
    // (TYPE_NAMES is emitted after type_names is computed, below.)
    // zenkey_for_each_payload_type! — the decode-dispatch hook: invokes the
    // caller's macro once per distinct type name across the registry set
    // (subjects, procedure request/reply, media attachments).
    let mut type_names: Vec<&str> = Vec::new();
    for f in files {
        for s in &f.subjects {
            type_names.push(&s.payload_type);
        }
        for p in &f.procedures {
            if let Some(t) = &p.request {
                type_names.push(t);
            }
            if let Some(t) = &p.reply {
                type_names.push(t);
            }
        }
        for m in &f.media {
            type_names.push(&m.attachment);
        }
    }
    type_names.sort_unstable();
    type_names.dedup();
    let _ = writeln!(
        out,
        "/// Every distinct payload type name this registry set references\n/// (subjects, procedure request/reply, media attachments) — sorted."
    );
    let _ = writeln!(out, "pub const TYPE_NAMES: &[&str] = &[");
    for t in &type_names {
        let _ = writeln!(out, "    {t:?},");
    }
    let _ = writeln!(out, "];\n");
    let _ = writeln!(
        out,
        "/// Invoke `$cb!(\"TypeName\")` once per distinct payload type name across\n/// every registry in this build (RFC 08 §5's type table, mechanically).\n#[macro_export]\nmacro_rules! zenkey_for_each_payload_type {{\n    ($cb:ident) => {{"
    );
    for t in &type_names {
        let _ = writeln!(out, "        $cb!({t:?});");
    }
    let _ = writeln!(out, "    }};\n}}\n");

    // is_registered_telemetry() — the check that makes RFC 08 §5's lint
    // non-vacuous.
    let _ = writeln!(
        out,
        "/// Is this telemetry metric name a registered subject of this producer?\n///\n/// `metric` is the telemetry subject tail, verbatim (the publisher appends it\n/// to `telemetry/<producer>`). This can only return `false` because the\n/// producer's telemetry tree is registered as real subject families rather\n/// than a `{{metric...}}` catch-all; producers whose metric tree is defined by\n/// a polled device keep a rest-var by design, so this is always `true` for\n/// them.\npub fn is_registered_telemetry(producer_name: &str, metric: &str) -> bool {{\n    let tail: Vec<&str> = metric.split('/').collect();\n    parse_subject(producer_name, {zk}::grammar::Class::Telemetry, &tail).is_some()\n}}"
    );

    out
}
