//! Code emission: linted registry files → the generated module source.

use std::fmt::Write as _;

use crate::{
    COMMON_STATE, Chunk, ProcedureEntry, RegistryFile, SubjectEntry, camel, producer_module, snake,
};

/// CamelCase -> snake_case for generated constructor/builder fn names.
pub(crate) fn camel_to_snake(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

pub(crate) fn emit(files: &[RegistryFile], zk: &str) -> String {
    let mut out =
        String::from("// @generated by zenkey-build from the registry dir — do not edit.\n\n");
    for f in files {
        let module = producer_module(&f.name);
        let _ = writeln!(out, "pub mod {module} {{");
        let _ = writeln!(out, "    #[allow(unused_imports)]");
        let _ = writeln!(
            out,
            "    use {zk}::grammar::{{self, Class, KeyError, Origin, Producer}};\n    #[allow(unused_imports)]\n    use {zk}::key::{{Chunk, Key, Selector}};\n    #[allow(unused_imports)]\n    use {zk}::origin::{{ConcreteOrigin, HostOrigin, LocalOrigin}};\n    #[allow(unused_imports)]\n    use {zk}::selector::Scope;"
        );
        let _ = writeln!(out, "    #[allow(unused_imports)]");
        let _ = writeln!(out, "    use {zk}::qos::QosProfile;");
        let _ = writeln!(
            out,
            "\n    /// The raw registry slice — served verbatim by `introspect` (RFC 08 §6).\n    pub const REGISTRY_TOML: &str = include_str!({:?});\n",
            f.toml_path
        );
        if let Some(origin) = &f.service_origin {
            let _ = writeln!(
                out,
                "    /// This is a service registry: keys omit the producer chunk.\n    pub fn origin() -> Origin {{ Origin::service({origin:?}).expect(\"validated at build time\") }}\n"
            );
        } else {
            let _ = writeln!(
                out,
                "    pub fn producer() -> Producer {{ Producer::new({:?}).expect(\"validated at build time\") }}\n",
                f.name
            );
        }

        // Subject enum.
        let _ = writeln!(out, "    #[derive(Debug, Clone, PartialEq, Eq)]");
        let _ = writeln!(out, "    pub enum Subject {{");
        for s in &f.subjects {
            let mut fields = String::new();
            for c in &s.chunks {
                match c {
                    Chunk::Var(v) => {
                        let _ = write!(fields, "{}: Chunk, ", snake(v));
                    }
                    Chunk::Rest(v) => {
                        let _ = write!(fields, "{}: Vec<Chunk>, ", snake(v));
                    }
                    Chunk::Literal(_) => {}
                }
            }
            if fields.is_empty() {
                let _ = writeln!(out, "        {},", s.variant);
            } else {
                let _ = writeln!(out, "        {} {{ {}}},", s.variant, fields);
            }
        }
        let _ = writeln!(out, "    }}\n");

        // impl Subject.
        let _ = writeln!(out, "    impl Subject {{");

        // Slug-at-boundary constructors (RFC 08 §1.2): call sites pass raw
        // application values, the constructor slugs — `slug_key_chunk()` at
        // call sites is retired. `{host}` vars in service registries take a
        // typed HostId (H4).
        for s in &f.subjects {
            if s.chunks.iter().all(|c| matches!(c, Chunk::Literal(_))) {
                continue;
            }
            let fn_name = camel_to_snake(&s.variant);
            let mut args = String::new();
            let mut inits = String::new();
            for c in &s.chunks {
                match c {
                    Chunk::Var(v) => {
                        let n = snake(v);
                        if f.service_origin.is_some() && v == "host" {
                            let _ = write!(args, "{n}: &{zk}::origin::HostId, ");
                            let _ = write!(inits, "{n}: Chunk::from_valid({n}.as_str()), ");
                        } else {
                            let _ = write!(args, "{n}: impl AsRef<str>, ");
                            let _ = write!(inits, "{n}: Chunk::slug({n}), ");
                        }
                    }
                    Chunk::Rest(v) => {
                        let n = snake(v);
                        let _ = write!(args, "{n}: impl IntoIterator<Item = impl AsRef<str>>, ");
                        let _ = write!(inits, "{n}: {n}.into_iter().map(Chunk::slug).collect(), ");
                    }
                    Chunk::Literal(_) => {}
                }
            }
            let _ = writeln!(
                out,
                "        /// Construct [`Subject::{}`], slugging variables (RFC 03 §2).\n        pub fn {fn_name}({args}) -> Self {{ Self::{} {{ {inits}}} }}\n",
                s.variant, s.variant
            );
        }

        // class()
        let _ = writeln!(out, "        pub fn class(&self) -> Class {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let class = match s.class.as_str() {
                "telemetry" => "Class::Telemetry",
                "state" => "Class::State",
                _ => "Class::Events",
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {class},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // qos()
        let _ = writeln!(out, "        pub fn qos(&self) -> QosProfile {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let qos = match s.qos.as_str() {
                "sampled" => "QosProfile::Sampled",
                "refreshed" => "QosProfile::Refreshed",
                "transition" => "QosProfile::Transition",
                "alert" => "QosProfile::Alert",
                _ => "QosProfile::Frame",
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {qos},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // ttl_s()
        let _ = writeln!(out, "        pub fn ttl_s(&self) -> Option<u64> {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let ttl = match s.ttl_s {
                Some(t) => format!("Some({t})"),
                None => "None".to_string(),
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {ttl},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // rate() — events rate class (RFC 04 §1.3), None for other classes.
        let _ = writeln!(out, "        pub fn rate(&self) -> Option<&'static str> {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let rate = match &s.rate {
                Some(r) => format!("Some({r:?})"),
                None => "None".to_string(),
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {rate},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // payload_type() — the registry `type` column (RFC 08 §2). One payload
        // type per pattern (P5), so this is what a consumer decodes as.
        let _ = writeln!(
            out,
            "        /// The one payload type of every expansion of this subject (RFC 08 §2)."
        );
        let _ = writeln!(out, "        pub fn payload_type(&self) -> &'static str {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {:?},",
                s.variant, s.payload_type
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // unit() — RFC 08 §4: the registry is authoritative for units, whether
        // or not the key spells one as a suffix.
        let _ = writeln!(out, "        pub fn unit(&self) -> Option<&'static str> {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let unit = match &s.unit {
                Some(u) => format!("Some({u:?})"),
                None => "None".to_string(),
            };
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {unit},",
                s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // cardinality() — the key-population bound the budget review enforces.
        let _ = writeln!(out, "        pub fn cardinality(&self) -> Option<u64> {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let c = match s.cardinality {
                Some(c) => format!("Some({c})"),
                None => "None".to_string(),
            };
            let _ = writeln!(out, "                Self::{} {{ .. }} => {c},", s.variant);
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // pattern()
        let _ = writeln!(out, "        pub fn pattern(&self) -> &'static str {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => {:?},",
                s.variant, s.path
            );
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // vars() — the variable bindings, in pattern order. A `{var...}` rest
        // binds as its chunks rejoined with `/`.
        let _ = writeln!(
            out,
            "        /// The pattern's variable bindings, in order (a `{{var...}}` rest rejoins with `/`)."
        );
        let _ = writeln!(
            out,
            "        pub fn vars(&self) -> Vec<(&'static str, String)> {{"
        );
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let mut binds = String::new();
            let mut body = String::from("vec![");
            for c in &s.chunks {
                match c {
                    Chunk::Literal(_) => {}
                    Chunk::Var(v) => {
                        let n = snake(v);
                        let _ = write!(binds, "{n}, ");
                        let _ = write!(body, "({v:?}, {n}.to_string()), ");
                    }
                    Chunk::Rest(v) => {
                        let n = snake(v);
                        let _ = write!(binds, "{n}, ");
                        let _ = write!(
                            body,
                            "({v:?}, {n}.iter().map(|c| c.as_str()).collect::<Vec<_>>().join(\"/\")), "
                        );
                    }
                }
            }
            body.push(']');
            let pat = if binds.is_empty() {
                format!("Self::{}", s.variant)
            } else {
                format!("Self::{} {{ {binds}}}", s.variant)
            };
            let _ = writeln!(out, "                {pat} => {body},");
        }
        let _ = writeln!(out, "            }}\n        }}\n");

        // parse(), precedence-ordered (RFC 08 §1: literal beats {var} beats
        // {var...}). Ordering is derived through `zenkey::pattern` — the same
        // primitive runtime tools match with — so generator and runtime can
        // never disagree (the parity test in fixture-tests pins it).
        let mut ordered: Vec<&SubjectEntry> = f.subjects.iter().collect();
        ordered.sort_by(|a, b| {
            let pa = zenkey::pattern::SubjectPattern::parse(&a.path).expect("linted");
            let pb = zenkey::pattern::SubjectPattern::parse(&b.path).expect("linted");
            pa.precedence().cmp(&pb.precedence())
        });
        let _ = writeln!(
            out,
            "        /// Refine a subject tail (chunks after the producer position).\n        pub fn parse(class: Class, tail: &[&str]) -> Option<Self> {{"
        );
        for s in &ordered {
            let class = match s.class.as_str() {
                "telemetry" => "Class::Telemetry",
                "state" => "Class::State",
                _ => "Class::Events",
            };
            let has_rest = matches!(s.chunks.last(), Some(Chunk::Rest(_)));
            let fixed = if has_rest {
                s.chunks.len() - 1
            } else {
                s.chunks.len()
            };
            let len_cond = if has_rest {
                if fixed == 0 {
                    "!tail.is_empty()".to_string()
                } else {
                    format!("tail.len() > {fixed}")
                }
            } else {
                format!("tail.len() == {fixed}")
            };
            let mut conds = vec![format!("class == {class}"), len_cond];
            for (i, c) in s.chunks.iter().enumerate() {
                if let Chunk::Literal(l) = c {
                    conds.push(format!("tail[{i}] == {l:?}"));
                }
            }
            let mut fields = String::new();
            for (i, c) in s.chunks.iter().enumerate() {
                match c {
                    Chunk::Var(v) => {
                        let _ = write!(fields, "{}: Chunk::from_valid(tail[{i}]), ", snake(v));
                    }
                    Chunk::Rest(v) => {
                        let _ = write!(
                            fields,
                            "{}: tail[{i}..].iter().map(|c| Chunk::from_valid(c)).collect(), ",
                            snake(v)
                        );
                    }
                    Chunk::Literal(_) => {}
                }
            }
            let construct = if fields.is_empty() {
                format!("Self::{}", s.variant)
            } else {
                format!("Self::{} {{ {fields}}}", s.variant)
            };
            let _ = writeln!(
                out,
                "            if {} {{ return Some({construct}); }}",
                conds.join(" && ")
            );
        }
        let _ = writeln!(out, "            None\n        }}\n");

        // parse_metric() — the ergonomic entry point. Consumers hold the
        // telemetry tail as one string (the telemetry metric name *is* the
        // subject tail, verbatim), so splitting it belongs here, once.
        let _ = writeln!(
            out,
            "        /// Refine a telemetry metric name (the subject tail as one `/`-joined string)."
        );
        let _ = writeln!(
            out,
            "        pub fn parse_metric(metric: &str) -> Option<Self> {{\n            let tail: Vec<&str> = metric.split('/').collect();\n            Self::parse(Class::Telemetry, &tail)\n        }}\n"
        );

        // family() — the fieldless mirror (RFC 08 §1.2).
        let _ = writeln!(
            out,
            "        /// This subject's family (the variant without its variables)."
        );
        let _ = writeln!(out, "        pub fn family(&self) -> Family {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let _ = writeln!(
                out,
                "                Self::{} {{ .. }} => Family::{},",
                s.variant, s.variant
            );
        }
        let _ = writeln!(out, "            }}\n        }}");
        let _ = writeln!(out, "    }}\n");

        // Family — consumer routing tables stop re-encoding the registry
        // (RFC 08 §1.2): fieldless ids with per-family selector builders.
        let _ = writeln!(
            out,
            "    /// Fieldless subject-family ids, with per-family selectors."
        );
        let _ = writeln!(
            out,
            "    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]"
        );
        let _ = writeln!(out, "    pub enum Family {{");
        for s in &f.subjects {
            let _ = writeln!(out, "        /// `{}` ({})", s.path, s.class);
            let _ = writeln!(out, "        {},", s.variant);
        }
        let _ = writeln!(out, "    }}\n");
        let _ = writeln!(out, "    impl Family {{");
        let _ = writeln!(out, "        pub const ALL: &[Family] = &[");
        for s in &f.subjects {
            let _ = writeln!(out, "            Family::{},", s.variant);
        }
        let _ = writeln!(out, "        ];\n");
        let _ = writeln!(out, "        pub fn class(self) -> Class {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let class = match s.class.as_str() {
                "telemetry" => "Class::Telemetry",
                "state" => "Class::State",
                _ => "Class::Events",
            };
            let _ = writeln!(out, "                Self::{} => {class},", s.variant);
        }
        let _ = writeln!(out, "            }}\n        }}\n");
        let _ = writeln!(out, "        pub fn pattern(self) -> &'static str {{");
        let _ = writeln!(out, "            match self {{");
        for s in &f.subjects {
            let _ = writeln!(out, "                Self::{} => {:?},", s.variant, s.path);
        }
        let _ = writeln!(out, "            }}\n        }}\n");
        // selector(): {var} -> *, {var...} -> **, precomputed at build time.
        let selector_tail = |chunks: &[Chunk]| -> String {
            let parts: Vec<&str> = chunks
                .iter()
                .map(|c| match c {
                    Chunk::Literal(l) => l.as_str(),
                    Chunk::Var(_) => "*",
                    Chunk::Rest(_) => "**",
                })
                .collect();
            parts.join("/")
        };
        if let Some(origin) = &f.service_origin {
            let _ = writeln!(
                out,
                "        /// The family's selector (service origin is fixed; RFC 08 §1.2)."
            );
            let _ = writeln!(out, "        pub fn selector(self) -> Selector {{");
            let _ = writeln!(out, "            match self {{");
            for s in &f.subjects {
                let class = &s.class;
                let tail = selector_tail(&s.chunks);
                let sel = format!("v1/{origin}/{class}/{tail}");
                let _ = writeln!(
                    out,
                    "                Self::{} => Selector::from_canonical({sel:?}.to_string()),",
                    s.variant
                );
            }
            let _ = writeln!(out, "            }}\n        }}");
        } else {
            let _ = writeln!(
                out,
                "        /// The family's selector in a scope: `{{var}}` -> `*`, `{{var...}}` -> `**` (RFC 08 §1.2)."
            );
            let _ = writeln!(
                out,
                "        pub fn selector(self, scope: Scope) -> Selector {{"
            );
            let _ = writeln!(out, "            match self {{");
            for s in &f.subjects {
                let class = &s.class;
                let tail = selector_tail(&s.chunks);
                let suffix = format!("/{class}/{}/{tail}", f.name);
                let _ = writeln!(
                    out,
                    "                Self::{} => Selector::from_canonical(format!(\"v1/{{}}{suffix}\", scope.chunk())),",
                    s.variant
                );
            }
            let _ = writeln!(out, "            }}\n        }}");
        }
        let _ = writeln!(out, "    }}\n");

        // Full-key builders: single-pass, infallible (fields are validated
        // Chunks; class/producer are registry constants). Publishing takes
        // the typed LocalOrigin (G5); addressing takes any host origin.
        let emit_subject_arms = |out: &mut String, subjects: &[SubjectEntry]| {
            for s in subjects {
                let mut binds = String::new();
                let mut body = String::new();
                let mut pending = String::new();
                let state_guard = s.class == "state";
                for c in &s.chunks {
                    match c {
                        Chunk::Literal(l) => {
                            pending.push('/');
                            pending.push_str(l);
                        }
                        Chunk::Var(v) => {
                            let n = snake(v);
                            let _ = write!(binds, "{n}, ");
                            pending.push('/');
                            if pending == "/" {
                                let _ = write!(body, "k.push('/'); ");
                            } else {
                                let _ = write!(body, "k.push_str({pending:?}); ");
                            }
                            pending.clear();
                            if state_guard {
                                let _ = write!(
                                    body,
                                    "assert!({n}.as_str() != \"alive\", \"reserved `alive` leaf (RFC 03 §3)\"); "
                                );
                            }
                            let _ = write!(body, "k.push_str({n}); ");
                        }
                        Chunk::Rest(v) => {
                            let n = snake(v);
                            let _ = write!(binds, "{n}, ");
                            if pending == "/" {
                                let _ = write!(body, "k.push('/'); ");
                                pending.clear();
                            } else if !pending.is_empty() {
                                let _ = write!(body, "k.push_str({pending:?}); ");
                                pending.clear();
                            }
                            if state_guard {
                                let _ = write!(
                                    body,
                                    "for c in {n} {{ assert!(c.as_str() != \"alive\", \"reserved `alive` leaf (RFC 03 §3)\"); k.push('/'); k.push_str(c); }} "
                                );
                            } else {
                                let _ =
                                    write!(body, "for c in {n} {{ k.push('/'); k.push_str(c); }} ");
                            }
                        }
                    }
                }
                if !pending.is_empty() {
                    let _ = write!(body, "k.push_str({pending:?}); ");
                }
                let pat = if binds.is_empty() {
                    format!("Subject::{}", s.variant)
                } else {
                    format!("Subject::{} {{ {binds}}}", s.variant)
                };
                let _ = writeln!(out, "            {pat} => {{ {body}}}");
            }
        };
        if let Some(origin) = &f.service_origin {
            let _ = writeln!(
                out,
                "    /// Base-relative data key for this service's subject (origin is fixed).\n    pub fn key(subject: &Subject) -> Key {{"
            );
            let _ = writeln!(
                out,
                "        let mut k = String::with_capacity(96);\n        k.push_str(\"v1/{origin}/\");\n        k.push_str(subject.class().chunk());\n        match subject {{"
            );
            emit_subject_arms(&mut out, &f.subjects);
            let _ = writeln!(out, "        }}\n        Key::from_canonical(k)\n    }}");
        } else {
            let _ = writeln!(
                out,
                "    /// Base-relative data key, published under this process's own origin\n    /// (RFC 08 §1.1/G5: publishing is Local by type).\n    pub fn key(o: &LocalOrigin, subject: &Subject) -> Key {{\n        key_impl(o.chunk(), {:?}, subject)\n    }}\n\n    /// Address one specific host's document (drill-down GETs, exact subscriptions).\n    pub fn key_at(o: &impl HostOrigin, subject: &Subject) -> Key {{\n        key_impl(o.chunk(), {:?}, subject)\n    }}\n\n    /// As [`key`], for an instance-suffixed producer (RFC 03 §1.5).\n    pub fn key_as(o: &LocalOrigin, producer: &Producer, subject: &Subject) -> Key {{\n        key_impl(o.chunk(), &producer.chunk(), subject)\n    }}",
                f.name, f.name
            );
            let _ = writeln!(
                out,
                "\n    fn key_impl(origin: &str, producer: &str, subject: &Subject) -> Key {{\n        let mut k = String::with_capacity(96);\n        k.push_str(\"v1/\");\n        k.push_str(origin);\n        k.push('/');\n        k.push_str(subject.class().chunk());\n        k.push('/');\n        k.push_str(producer);\n        match subject {{"
            );
            emit_subject_arms(&mut out, &f.subjects);
            let _ = writeln!(out, "        }}\n        Key::from_canonical(k)\n    }}");
        }

        // Procedures.
        if !f.procedures.is_empty() {
            let _ = writeln!(out, "\n    #[derive(Debug, Clone, Copy, PartialEq, Eq)]");
            let _ = writeln!(out, "    pub enum ProcedureId {{");
            for p in &f.procedures {
                let _ = writeln!(out, "        /// `{}` ({})", p.path, p.kind);
                let _ = writeln!(out, "        {},", p.variant);
            }
            let _ = writeln!(out, "    }}\n");
            let _ = writeln!(out, "    impl ProcedureId {{");
            let _ = writeln!(out, "        pub const ALL: &[ProcedureId] = &[");
            for p in &f.procedures {
                let _ = writeln!(out, "            ProcedureId::{},", p.variant);
            }
            let _ = writeln!(out, "        ];\n");
            let _ = writeln!(
                out,
                "        pub fn chunks(self) -> &'static [&'static str] {{"
            );
            let _ = writeln!(out, "            match self {{");
            for p in &f.procedures {
                let list: Vec<String> = p
                    .chunks
                    .iter()
                    .map(|c| match c {
                        Chunk::Literal(l) => format!("{l:?}"),
                        Chunk::Var(v) | Chunk::Rest(v) => format!("{:?}", format!("{{{v}}}")),
                    })
                    .collect();
                let _ = writeln!(
                    out,
                    "                Self::{} => &[{}],",
                    p.variant,
                    list.join(", ")
                );
            }
            let _ = writeln!(out, "            }}\n        }}\n");
            let _ = writeln!(out, "        pub fn kind(self) -> &'static str {{");
            let _ = writeln!(out, "            match self {{");
            for p in &f.procedures {
                let _ = writeln!(out, "                Self::{} => {:?},", p.variant, p.kind);
            }
            let _ = writeln!(out, "            }}\n        }}\n");
            let _ = writeln!(
                out,
                "        /// The registered path, e.g. `artifact/request`."
            );
            let _ = writeln!(out, "        pub fn path(self) -> &'static str {{");
            let _ = writeln!(out, "            match self {{");
            for p in &f.procedures {
                let _ = writeln!(out, "                Self::{} => {:?},", p.variant, p.path);
            }
            let _ = writeln!(out, "            }}\n        }}\n");
            // request_type()/reply_type() — RFC 08 §2. A `read` has no request
            // body; a write that acks with nothing has no reply type.
            for (method, field) in [
                ("request_type", &|p: &ProcedureEntry| {
                    p.request.clone() as Option<String>
                }),
                ("reply_type", &|p: &ProcedureEntry| {
                    p.reply.clone() as Option<String>
                }),
            ]
                as [(&str, &dyn Fn(&ProcedureEntry) -> Option<String>); 2]
            {
                let _ = writeln!(
                    out,
                    "        pub fn {method}(self) -> Option<&'static str> {{"
                );
                let _ = writeln!(out, "            match self {{");
                for p in &f.procedures {
                    let t = match field(p) {
                        Some(t) => format!("Some({t:?})"),
                        None => "None".to_string(),
                    };
                    let _ = writeln!(out, "                Self::{} => {t},", p.variant);
                }
                let _ = writeln!(out, "            }}\n        }}\n");
            }
            let _ = writeln!(out, "    }}\n");
            if f.service_origin.is_some() {
                let _ = writeln!(
                    out,
                    "    /// Base-relative `@rpc` key for this service's procedure.\n    /// Errs on a `{{var}}`-bearing pattern — use [`rpc_key_with`].\n    pub fn rpc_key(p: ProcedureId) -> Result<Key, KeyError> {{\n        grammar::rpc_key(&origin(), None, p.chunks())\n    }}\n\n    /// As [`rpc_key`], substituting the pattern's `{{var}}` chunks in order\n    /// (RFC 09 G6: the actuated resource rides the path, typed).\n    pub fn rpc_key_with(p: ProcedureId, vars: &[&str]) -> Result<Key, KeyError> {{\n        let chunks = substitute_procedure_vars(p, vars)?;\n        let refs: Vec<&str> = chunks.iter().map(String::as_str).collect();\n        grammar::rpc_key(&origin(), None, &refs)\n    }}\n\n    /// The serve-side selector: every `{{var}}` becomes `*`. A selector, not a\n    /// buildable key.\n    pub fn rpc_serve_key(p: ProcedureId) -> String {{\n        let mut key = format!(\"{{}}/{{}}/{{}}\", grammar::VERSION_CHUNK, origin().chunk(), grammar::PLANE_RPC);\n        for c in p.chunks() {{\n            key.push('/');\n            key.push_str(if c.starts_with('{{') {{ \"*\" }} else {{ c }});\n        }}\n        key\n    }}"
                );
            } else {
                let _ = writeln!(
                    out,
                    "    /// Base-relative `@rpc` key for this producer's procedure.\n    /// Errs on a `{{var}}`-bearing pattern — use [`rpc_key_with`].\n    pub fn rpc_key(origin: &Origin, p: ProcedureId) -> Result<Key, KeyError> {{\n        grammar::rpc_key(origin, Some(&producer()), p.chunks())\n    }}\n\n    /// As [`rpc_key`], substituting the pattern's `{{var}}` chunks in order\n    /// (RFC 09 G6: the actuated resource rides the path, typed).\n    pub fn rpc_key_with(origin: &Origin, p: ProcedureId, vars: &[&str]) -> Result<Key, KeyError> {{\n        let chunks = substitute_procedure_vars(p, vars)?;\n        let refs: Vec<&str> = chunks.iter().map(String::as_str).collect();\n        grammar::rpc_key(origin, Some(&producer()), &refs)\n    }}\n\n    /// The serve-side selector: every `{{var}}` becomes `*`. A selector, not a\n    /// buildable key.\n    pub fn rpc_serve_key(origin: &Origin, p: ProcedureId) -> String {{\n        let mut key = format!(\"{{}}/{{}}/{{}}/{{}}\", grammar::VERSION_CHUNK, origin.chunk(), grammar::PLANE_RPC, producer().chunk());\n        for c in p.chunks() {{\n            key.push('/');\n            key.push_str(if c.starts_with('{{') {{ \"*\" }} else {{ c }});\n        }}\n        key\n    }}"
                );
            }
            // Shared var-substitution helper for rpc_key_with.
            let _ = writeln!(
                out,
                "\n    fn substitute_procedure_vars(p: ProcedureId, vars: &[&str]) -> Result<Vec<String>, KeyError> {{\n        let needed = p.chunks().iter().filter(|c| c.starts_with('{{')).count();\n        if needed != vars.len() {{\n            return Err(KeyError::Parse(format!(\n                \"procedure {{}} takes {{needed}} variable(s), got {{}}\", p.path(), vars.len()\n            )));\n        }}\n        let mut vi = 0usize;\n        Ok(p.chunks().iter().map(|c| {{\n            if c.starts_with('{{') {{ let v = vars[vi].to_string(); vi += 1; v }} else {{ (*c).to_string() }}\n        }}).collect())\n    }}"
            );
        }

        let _ = writeln!(out, "}}\n");
    }

    // Raw registry slice by producer name (introspect, RFC 08 §6).
    let _ = writeln!(
        out,
        "/// The raw registry slice for a producer/service, by base name."
    );
    let _ = writeln!(
        out,
        "pub fn registry_toml(name: &str) -> Option<&'static str> {{"
    );
    let _ = writeln!(out, "    match name {{");
    for f in files {
        let module = producer_module(&f.name);
        let _ = writeln!(
            out,
            "        {:?} => Some({module}::REGISTRY_TOML),",
            f.name
        );
    }
    let _ = writeln!(out, "        _ => None,\n    }}\n}}\n");

    // Every registry slice this build was compiled against, by base name. A
    // fleet-capabilities view fans `introspect` out over exactly this list and
    // diffs each reply against the local slice.
    let _ = writeln!(
        out,
        "/// Every producer/service this build knows, with its raw registry slice."
    );
    let _ = writeln!(out, "pub const REGISTRIES: &[(&str, &str)] = &[");
    for f in files {
        let module = producer_module(&f.name);
        let _ = writeln!(out, "    ({:?}, {module}::REGISTRY_TOML),", f.name);
    }
    let _ = writeln!(out, "];\n");

    // Cross-producer dispatch: refine a structural key into (producer, subject).
    let _ = writeln!(out, "/// Refined subject from any registered producer.");
    let _ = writeln!(out, "#[derive(Debug, Clone, PartialEq, Eq)]");
    let _ = writeln!(out, "pub enum AnySubject {{");
    for f in files {
        let module = producer_module(&f.name);
        let _ = writeln!(out, "    {}({module}::Subject),", camel(&[f.name.as_str()]));
    }
    let _ = writeln!(out, "}}\n");

    // AnySubject accessors: producer-agnostic introspection of a refined
    // subject. `vars()` is what lets a consumer read `{iface}` by name instead
    // of by position.
    let _ = writeln!(out, "impl AnySubject {{");
    for (method, ret, body) in [
        ("producer_name", "&'static str".to_string(), "NAME"),
        ("class", format!("{zk}::grammar::Class"), "s.class()"),
        ("pattern", "&'static str".to_string(), "s.pattern()"),
        (
            "vars",
            "Vec<(&'static str, String)>".to_string(),
            "s.vars()",
        ),
        (
            "payload_type",
            "&'static str".to_string(),
            "s.payload_type()",
        ),
        ("unit", "Option<&'static str>".to_string(), "s.unit()"),
        ("cardinality", "Option<u64>".to_string(), "s.cardinality()"),
        ("qos", format!("{zk}::qos::QosProfile"), "s.qos()"),
        ("ttl_s", "Option<u64>".to_string(), "s.ttl_s()"),
        ("rate", "Option<&'static str>".to_string(), "s.rate()"),
    ] {
        let _ = writeln!(out, "    pub fn {method}(&self) -> {ret} {{");
        let _ = writeln!(out, "        match self {{");
        for f in files {
            let variant = camel(&[f.name.as_str()]);
            let arm = if body == "NAME" {
                format!("{:?}", f.name)
            } else {
                body.to_string()
            };
            let bind = if body == "NAME" { "_" } else { "s" };
            let _ = writeln!(out, "            Self::{variant}({bind}) => {arm},");
        }
        let _ = writeln!(out, "        }}\n    }}\n");
    }
    let _ = writeln!(out, "}}\n");

    // AnySubject::common_state() — refine any producer's state subject into
    // the RFC-defined framework set. Driven by the `common = "..."` field on
    // registry entries, so it cannot drift from the registry: drop the field
    // (or the subject) and its arm disappears here.
    let _ = writeln!(out, "impl AnySubject {{");
    let _ = writeln!(
        out,
        "    /// The framework state subject this refines to, if any.\n    pub fn common_state(&self) -> Option<{zk}::common_state::CommonState<'_>> {{\n        use {zk}::common_state::CommonState as C;\n        match self {{"
    );
    for f in files {
        let module = producer_module(&f.name);
        let variant = camel(&[f.name.as_str()]);
        let _ = writeln!(out, "            Self::{variant}(s) => match s {{");
        let mut mapped = 0usize;
        for s in &f.subjects {
            let Some(common) = &s.common else { continue };
            let (_, ctor, _) = COMMON_STATE
                .iter()
                .find(|(n, _, _)| n == common)
                .expect("common name validated at load time");
            mapped += 1;
            // Bind the pattern's variables by name; the CommonState ctor uses
            // the same names (linted at load time), so field-init shorthand
            // lines them up.
            let binds: Vec<String> = s
                .chunks
                .iter()
                .filter_map(|c| match c {
                    Chunk::Var(v) | Chunk::Rest(v) => Some(snake(v)),
                    Chunk::Literal(_) => None,
                })
                .collect();
            let pat = if binds.is_empty() {
                format!("{module}::Subject::{}", s.variant)
            } else {
                format!(
                    "{module}::Subject::{} {{ {} }}",
                    s.variant,
                    binds.join(", ")
                )
            };
            let _ = writeln!(out, "                {pat} => Some(C::{ctor}),");
        }
        // A producer whose every subject is a framework one (an `@catalog`
        // service) leaves nothing for a wildcard arm to catch.
        if mapped < f.subjects.len() {
            let _ = writeln!(out, "                _ => None,");
        }
        let _ = writeln!(out, "            }},");
    }
    let _ = writeln!(out, "        }}\n    }}\n}}\n");

    let _ = writeln!(
        out,
        "/// Registry-refine a structurally parsed key (RFC 08 §1 parse direction).\n/// `producer_name` is the *base* name (instance suffix already stripped by\n/// `Producer::parse_chunk`); service keys pass the service\n/// name (e.g. \"catalog\").\npub fn parse_subject(producer_name: &str, class: {zk}::grammar::Class, tail: &[&str]) -> Option<AnySubject> {{"
    );
    let _ = writeln!(out, "    match producer_name {{");
    for f in files {
        let module = producer_module(&f.name);
        let _ = writeln!(
            out,
            "        {:?} => {module}::Subject::parse(class, tail).map(AnySubject::{}),",
            f.name,
            camel(&[f.name.as_str()])
        );
    }
    let _ = writeln!(out, "        _ => None,\n    }}\n}}\n");

    // is_registered_telemetry() — the check that makes RFC 08 §5's lint
    // non-vacuous.
    let _ = writeln!(
        out,
        "/// Is this telemetry metric name a registered subject of this producer?\n///\n/// `metric` is the telemetry subject tail, verbatim (the publisher appends it\n/// to `telemetry/<producer>`). This can only return `false` because the\n/// producer's telemetry tree is registered as real subject families rather\n/// than a `{{metric...}}` catch-all; producers whose metric tree is defined by\n/// a polled device keep a rest-var by design, so this is always `true` for\n/// them.\npub fn is_registered_telemetry(producer_name: &str, metric: &str) -> bool {{\n    let tail: Vec<&str> = metric.split('/').collect();\n    parse_subject(producer_name, {zk}::grammar::Class::Telemetry, &tail).is_some()\n}}"
    );

    out
}
