//! The vocabulary of a call that needs no session (spec §5, #611): what a
//! handler receives and refuses with, and what a caller gets back.
//!
//! Serving is [`crate::operation`]'s and calling [`crate::client`]'s; both
//! need zenoh. These types do not, so a contract crate's `Handlers` and
//! `Api` traits (generated by `zenkey-build`) are written in them and build
//! without zenoh (`default-features = false`).
//!
//! - **A handler** receives its decoded request and a [`CallInfo`] (the
//!   template values, the claimed metadata of O7), and answers a value or
//!   an [`OpError`], the error envelope of §5.2. A `replies = "many"`
//!   handler sends through a [`Sink`]: values, then the summary (O6).
//! - **A caller** gets an [`Outcome`] (O5: a value, a refusal, a malformed
//!   refusal, or silence, each distinct) or, for a many-reply or fan-out
//!   call, [`Replies`], attributed by replier (O3, O6).

use std::fmt;
use std::future::Future;
use std::pin::Pin;
use std::sync::{Arc, Mutex, OnceLock};

use serde::{Deserialize, Serialize};
use zenkey_model::authoring::Encoding as WireEncoding;
use zenkey_model::contract::Operation;
use zenkey_model::descriptor::Cause;
use zenkey_model::envelope::{Detail, Envelope, EnvelopeError};
use zenkey_model::grammar::Addr;
use zenkey_model::template::Bindings;

use crate::codec::Codec;
use crate::error::{Error, Result};

/// The optional call metadata (O7): who claims to call, and the caller's
/// id for the request. It travels as the request's attachment, the JSON
/// object `{"actor", "request_id"}`. Claimed, never authentication: any
/// session can write any value here.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct CallMetadata {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub actor: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl CallMetadata {
    #[must_use]
    pub fn new(actor: &str, request_id: &str) -> Self {
        Self {
            actor: Some(actor.to_owned()),
            request_id: Some(request_id.to_owned()),
        }
    }

    /// The attachment's bytes.
    #[must_use]
    pub fn to_bytes(&self) -> Vec<u8> {
        serde_json::to_vec(self).expect("two optional strings serialize")
    }

    /// Reads an attachment as call metadata: a JSON object whose `actor`
    /// and `request_id`, when present, are strings. Other members are
    /// ignored. Anything else is not call metadata, and `None`.
    #[must_use]
    pub fn from_bytes(bytes: &[u8]) -> Option<Self> {
        let serde_json::Value::Object(m) = serde_json::from_slice(bytes).ok()? else {
            return None;
        };
        let text = |k: &str| match m.get(k) {
            None => Some(None),
            Some(serde_json::Value::String(s)) => Some(Some(s.clone())),
            Some(_) => None,
        };
        Some(Self {
            actor: text("actor")?,
            request_id: text("request_id")?,
        })
    }
}

/// A failed call, as its owner refuses it (O3): the error envelope of §5.2.
/// The runtime encodes it as the operation's types say.
#[derive(Debug, Clone, PartialEq)]
pub struct OpError(Envelope);

/// The name §5.2 gives a cause.
#[must_use]
pub fn cause_name(c: Cause) -> &'static str {
    match c {
        Cause::Build => "build",
        Cause::Config => "config",
        Cause::Capability => "capability",
    }
}

impl OpError {
    fn new(code: &str, message: impl Into<String>, cause: Option<Cause>) -> Self {
        Self(Envelope {
            code: code.to_owned(),
            message: message.into(),
            cause: cause.map(|c| cause_name(c).to_owned()),
            detail: None,
        })
    }

    /// The request does not decode, or breaks the operation's rules.
    pub fn invalid_request(message: impl Into<String>) -> Self {
        Self::new("invalid_request", message, None)
    }

    pub fn not_found(message: impl Into<String>) -> Self {
        Self::new("not_found", message, None)
    }

    /// The operation is not available here, and why (§2.3, §3.3).
    pub fn unavailable(cause: Cause, message: impl Into<String>) -> Self {
        Self::new("unavailable", message, Some(cause))
    }

    pub fn forbidden(message: impl Into<String>) -> Self {
        Self::new("forbidden", message, None)
    }

    pub fn busy(message: impl Into<String>) -> Self {
        Self::new("busy", message, None)
    }

    pub fn internal(message: impl Into<String>) -> Self {
        Self::new("internal", message, None)
    }

    /// The runtime's alone (O2): a handler never sees a fan-out call to an
    /// operation that forbids one.
    #[cfg_attr(not(feature = "zenoh"), allow(dead_code))]
    pub(crate) fn fanout_forbidden(message: impl Into<String>) -> Self {
        Self::new("fanout_forbidden", message, None)
    }

    /// `app` with no detail (§5.2, 0.7, F-65): the operation's own failure,
    /// which any operation may refuse with. The only `app` for an operation
    /// that declares no `error` type, which has no detail to send; with one,
    /// the detail is optional.
    pub fn app_without_detail(message: impl Into<String>) -> Self {
        Self::new("app", message, None)
    }

    /// `app`, with a value of the operation's declared `error` type: for a
    /// JSON or CBOR envelope (§5.2). On an operation that declares no
    /// `error` type, the runtime sends `internal` instead
    /// ([`OpError::app_without_detail`] is that operation's `app`).
    pub fn app<T: Serialize>(message: impl Into<String>, detail: &T) -> Self {
        match serde_json::to_value(detail) {
            Ok(v) => Self(Envelope {
                code: "app".to_owned(),
                message: message.into(),
                cause: None,
                detail: Some(Detail::Value(v)),
            }),
            Err(e) => Self::internal(format!("the app detail does not serialize: {e}")),
        }
    }

    /// `app`, with the declared `error` type's value already encoded: a
    /// protobuf message, carried as the envelope's bytes, or a raw type's
    /// bytes, which the runtime sends as base64 text in its JSON envelope
    /// (§5.2, 0.7, F-65).
    pub fn app_bytes(message: impl Into<String>, detail: Vec<u8>) -> Self {
        Self(Envelope {
            code: "app".to_owned(),
            message: message.into(),
            cause: None,
            detail: Some(Detail::Bytes(detail)),
        })
    }

    /// `app`, with a value of the declared `error` type through its codec:
    /// a protobuf message is encoded into the envelope's bytes, a JSON
    /// Schema value carried as a value, a raw type's bytes as base64 text
    /// (§5.2). Generated code names the codec; a handler writes
    /// `OpError::app_as::<Protobuf<NavError>>(…)`.
    pub fn app_as<C: Codec>(message: impl Into<String>, detail: &C::Value) -> Self {
        match C::detail(detail) {
            Ok(d) => Self(Envelope {
                code: "app".to_owned(),
                message: message.into(),
                cause: None,
                detail: Some(d),
            }),
            Err(e) => Self::internal(format!("the app detail does not encode: {e}")),
        }
    }

    #[must_use]
    pub fn code(&self) -> &str {
        &self.0.code
    }

    #[must_use]
    pub fn envelope(&self) -> &Envelope {
        &self.0
    }

    #[must_use]
    pub fn into_envelope(self) -> Envelope {
        self.0
    }
}

impl fmt::Display for OpError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}: {}", self.0.code, self.0.message)
    }
}

impl std::error::Error for OpError {}

/// A runtime error inside a handler is the owner's failure: `internal`.
impl From<Error> for OpError {
    fn from(e: Error) -> Self {
        Self::internal(e.to_string())
    }
}

/// An envelope received from elsewhere (a proxy relaying a refusal).
impl From<Envelope> for OpError {
    fn from(e: Envelope) -> Self {
        Self(e)
    }
}

/// What a typed handler knows of its call, besides the request: the member
/// it answers for, what the key called binds, and the metadata the caller
/// claims (O7). With the `zenoh` feature, the runtime's
/// [`crate::operation::Call`] stays reachable ([`CallInfo::call`]).
///
/// **Over a template** (§5.1, 0.7, O-1, C-2): a fan-out's key expression can
/// hold a wildcard where the template has a parameter, so it names no
/// member. A handler served over the whole template learns only what the
/// key binds ([`CallInfo::bound`]), names the member its reply answers for
/// ([`CallInfo::member`]), and the reply goes on that member's key. When
/// the key binds every parameter, the runtime has named it already.
/// Clones share the naming, as the runtime's call's clones do.
#[derive(Clone, Default)]
pub struct CallInfo {
    /// The member's values, without a bus: given, or named once.
    member: Arc<OnceLock<Bindings>>,
    bound: Bindings,
    metadata: Option<CallMetadata>,
    fanout: bool,
    #[cfg(feature = "zenoh")]
    call: Option<crate::operation::Call>,
}

impl fmt::Debug for CallInfo {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("CallInfo")
            .field("values", &self.values())
            .field("bound", &self.bound)
            .field("metadata", &self.metadata)
            .field("fanout", &self.fanout)
            .finish_non_exhaustive()
    }
}

impl CallInfo {
    /// A concrete call with these template values and metadata: what a
    /// test drives a handler with, without a bus.
    #[must_use]
    pub fn new(values: Bindings, metadata: Option<CallMetadata>) -> Self {
        Self {
            member: Arc::new(OnceLock::from(values.clone())),
            bound: values,
            metadata,
            ..Self::default()
        }
    }

    /// A fan-out call whose key binds `bound` of the template's parameters
    /// and no other: what a test drives a template-wide handler with,
    /// without a bus. Keep a clone to read the member the handler names.
    #[must_use]
    pub fn fan_out(bound: Bindings, metadata: Option<CallMetadata>) -> Self {
        Self {
            bound,
            metadata,
            fanout: true,
            ..Self::default()
        }
    }

    #[cfg(feature = "zenoh")]
    pub(crate) fn of(call: &crate::operation::Call) -> Self {
        Self {
            member: Arc::default(),
            bound: call.bound().clone(),
            metadata: call.metadata().cloned(),
            fanout: !call.is_concrete(),
            call: Some(call.clone()),
        }
    }

    /// The template's values, unslugged, of the member this call answers
    /// for: the concrete key called, the member a server was declared on,
    /// or the member named ([`CallInfo::member`]). `None` for a fan-out over
    /// a template until a member is named.
    #[must_use]
    pub fn values(&self) -> Option<&Bindings> {
        #[cfg(feature = "zenoh")]
        if let Some(c) = &self.call {
            return c.values();
        }
        self.member.get()
    }

    /// What the key called binds (§5.1, "Over a template"): each parameter
    /// at a concrete chunk, unslugged, and none at a wildcard. Every
    /// parameter, for a concrete call.
    #[must_use]
    pub fn bound(&self) -> &Bindings {
        &self.bound
    }

    /// Names the member this call answers for (§5.1, "Over a template"):
    /// its replies go on that member's key, which the call must have
    /// selected. A call answers for one member, so naming another after one
    /// is named is refused; naming the same one again is not. Without a
    /// member, a fan-out over a template has no key to reply on, and is
    /// answered `internal` (O3).
    ///
    /// Without a bus, `values` must agree with what the key bound.
    pub fn member(&self, values: &Bindings) -> Result<()> {
        #[cfg(feature = "zenoh")]
        if let Some(c) = &self.call {
            return c.member(values);
        }
        if let Some((k, v)) = self.bound.iter().find(|(k, v)| values.get(*k) != Some(*v)) {
            return Err(Error::Contract(format!(
                "parameter {k:?} is {v:?} in the key called: not a member this call selected"
            )));
        }
        let named = self.member.get_or_init(|| values.clone());
        if named == values {
            Ok(())
        } else {
            Err(Error::Contract(format!(
                "this call answers for {named:?} already: one member per call (§5.1)"
            )))
        }
    }

    /// The value of one single-chunk template parameter.
    #[must_use]
    pub fn value(&self, param: &str) -> Option<&str> {
        self.values()?.get(param)?.first().map(String::as_str)
    }

    /// The call metadata the caller claims (O7).
    #[must_use]
    pub fn metadata(&self) -> Option<&CallMetadata> {
        self.metadata.as_ref()
    }

    /// Whether the call named one concrete key; only a `fanout = "allowed"`
    /// operation is ever called otherwise (O2).
    #[must_use]
    pub fn is_concrete(&self) -> bool {
        !self.fanout
    }

    /// The runtime's call, when it came over a bus.
    #[cfg(feature = "zenoh")]
    #[must_use]
    pub fn call(&self) -> Option<&crate::operation::Call> {
        self.call.as_ref()
    }
}

/// A boxed future, for the object-safe [`ReplyOut`].
pub type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// Where a [`Sink`]'s encoded replies go: the runtime's call (O6), or
/// anything a test supplies.
pub trait ReplyOut: Send + Sync {
    /// One value reply, encoded as the `response` type.
    fn value(&self, bytes: Vec<u8>) -> BoxFuture<'_, Result<()>>;
    /// The summary reply, encoded as the `summary` type: the last (O6).
    fn summary(&self, bytes: Vec<u8>) -> BoxFuture<'_, Result<()>>;
}

/// What a [`Sink::memory`] collected.
#[derive(Debug)]
pub struct Collected<T, S> {
    pub values: Vec<T>,
    pub summary: Option<S>,
}

type Encode<T> = fn(&T, Option<WireEncoding>) -> std::result::Result<Vec<u8>, String>;

enum SinkInner<T, S> {
    Wire {
        out: Arc<dyn ReplyOut>,
        wire: Option<WireEncoding>,
        value: Encode<T>,
        summary: Encode<S>,
    },
    Memory(Arc<Mutex<Collected<T, S>>>),
}

/// A `replies = "many"` handler's replies (O6): any number of values, then
/// at most one summary, which ends the call. Encoding is the codec's and the
/// contract's, never the handler's (§7.2).
pub struct Sink<T, S = ()> {
    inner: SinkInner<T, S>,
}

impl<T: Send + 'static, S: Send + 'static> Sink<T, S> {
    /// A sink encoding through the codecs `C` (values) and `CS` (summary)
    /// in the operation's wire encoding, onto `out`.
    pub fn new<C, CS>(out: Arc<dyn ReplyOut>, wire: Option<WireEncoding>) -> Self
    where
        C: Codec<Value = T>,
        CS: Codec<Value = S>,
    {
        Self {
            inner: SinkInner::Wire {
                out,
                wire,
                value: C::encode,
                summary: CS::encode,
            },
        }
    }

    /// A sink that keeps what it is sent: for driving a handler in a test,
    /// without a bus.
    #[must_use]
    pub fn memory() -> (Self, Arc<Mutex<Collected<T, S>>>) {
        let c = Arc::new(Mutex::new(Collected {
            values: Vec::new(),
            summary: None,
        }));
        (
            Self {
                inner: SinkInner::Memory(Arc::clone(&c)),
            },
            c,
        )
    }

    /// Sends one value.
    pub async fn send(&self, value: T) -> Result<()> {
        match &self.inner {
            SinkInner::Wire {
                out,
                wire,
                value: enc,
                ..
            } => {
                let bytes = enc(&value, *wire).map_err(Error::Payload)?;
                out.value(bytes).await
            }
            SinkInner::Memory(c) => {
                let mut c = c.lock().expect("not poisoned");
                if c.summary.is_some() {
                    return Err(Error::Contract("the summary ended the call (O6)".into()));
                }
                c.values.push(value);
                Ok(())
            }
        }
    }

    /// Sends the summary, which ends the call (O6). Only for an operation
    /// that declares one.
    pub async fn summary(&self, summary: S) -> Result<()> {
        match &self.inner {
            SinkInner::Wire {
                out,
                wire,
                summary: enc,
                ..
            } => {
                let bytes = enc(&summary, *wire).map_err(Error::Payload)?;
                out.summary(bytes).await
            }
            SinkInner::Memory(c) => {
                let mut c = c.lock().expect("not poisoned");
                if c.summary.is_some() {
                    return Err(Error::Contract("the summary ended the call (O6)".into()));
                }
                c.summary = Some(summary);
                Ok(())
            }
        }
    }
}

/// An error reply that claims an envelope encoding and is not an envelope
/// (§5.2's decoding refusals): a broken server, not a silent one.
#[derive(Debug, Clone, PartialEq)]
pub struct Malformed {
    pub encoding: String,
    pub error: EnvelopeError,
}

/// What presence says of a service that did not answer (O5).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Attribution {
    /// It holds the interface's token: it is up and did not answer. The
    /// access control refused the call, the server is frozen, or the reply
    /// was lost.
    Present,
    /// It holds an instance token, not this interface's: a standby, or the
    /// interface is in its tokenless set (§8.1).
    InstanceOnly,
    /// No token of the service is visible.
    Absent,
    /// Presence cannot be observed from here (R7): a constrained face.
    Unobservable,
}

/// No answer (O5): no value and no envelope.
#[derive(Debug, Clone, PartialEq)]
pub struct Silence {
    /// Calls made: more than one only for an idempotent operation (O4).
    pub attempts: u32,
    /// The transport's last error reply, such as `zenoh/string: Timeout`.
    pub transport: Option<String>,
    pub presence: Attribution,
}

/// The outcome of a one-reply call. Each case is distinct: silence is never
/// an error reply, and never a verdict (O5). The runtime's client answers
/// `Outcome<Answer>` (the sample, attributed); a typed client, the decoded
/// response.
#[derive(Debug, Clone)]
pub enum Outcome<T> {
    /// A value reply on the operation's concrete key.
    Value(T),
    /// A `reply_err` carrying a valid envelope (O3).
    Refused(Envelope),
    /// A `reply_err` claiming an envelope encoding that does not decode.
    Malformed(Malformed),
    /// No answer.
    NoAnswer(Silence),
}

impl<T> Outcome<T> {
    /// The value reply, if that is what came.
    #[must_use]
    pub fn answer(&self) -> Option<&T> {
        match self {
            Self::Value(a) => Some(a),
            _ => None,
        }
    }

    #[must_use]
    pub fn refusal(&self) -> Option<&Envelope> {
        match self {
            Self::Refused(e) => Some(e),
            _ => None,
        }
    }

    #[must_use]
    pub fn silence(&self) -> Option<&Silence> {
        match self {
            Self::NoAnswer(s) => Some(s),
            _ => None,
        }
    }

    /// The value, decoded or replaced; the other cases unchanged.
    pub fn try_map<U, E>(
        self,
        f: impl FnOnce(T) -> std::result::Result<U, E>,
    ) -> std::result::Result<Outcome<U>, E> {
        Ok(match self {
            Self::Value(v) => Outcome::Value(f(v)?),
            Self::Refused(e) => Outcome::Refused(e),
            Self::Malformed(m) => Outcome::Malformed(m),
            Self::NoAnswer(s) => Outcome::NoAnswer(s),
        })
    }
}

/// Every value and summary one concrete key carried (O6).
#[derive(Debug, Clone)]
pub struct Replier<V, S> {
    pub addr: Addr,
    /// The operation key the replies went on.
    pub key: String,
    /// Its template's values, unslugged.
    pub params: Bindings,
    pub values: Vec<V>,
    /// Summary replies: exactly one when the replier finished (O6). Two
    /// instances replying on one key (a split-brain, `replicated`) give two.
    pub summaries: Vec<S>,
}

impl<V, S> Replier<V, S> {
    /// The summary, when exactly one arrived.
    #[must_use]
    pub fn summary(&self) -> Option<&S> {
        match self.summaries.as_slice() {
            [s] => Some(s),
            _ => None,
        }
    }
}

/// Every reply to a many-reply or fan-out call, attributed (O6).
#[derive(Debug, Clone)]
pub struct Replies<V, S> {
    /// Whether the operation declares a `summary`, so that a replier's
    /// completion can be told.
    pub summary_declared: bool,
    /// One per concrete key, in the order of first arrival.
    pub repliers: Vec<Replier<V, S>>,
    /// Envelopes. A `reply_err` carries no key, so a refusal is never
    /// attributed to a replier.
    pub refusals: Vec<Envelope>,
    pub malformed: Vec<Malformed>,
    /// The transport's error replies, such as a timeout.
    pub transport: Vec<String>,
    /// Value replies discarded: on a key that is not concrete (R6), or not
    /// a member of the operation called.
    pub discarded: u64,
}

impl<V, S> Default for Replies<V, S> {
    fn default() -> Self {
        Self {
            summary_declared: false,
            repliers: Vec::new(),
            refusals: Vec::new(),
            malformed: Vec::new(),
            transport: Vec::new(),
            discarded: 0,
        }
    }
}

impl<V, S> Replies<V, S> {
    #[cfg_attr(not(feature = "zenoh"), allow(dead_code))]
    pub(crate) fn new(op: &Operation) -> Self {
        Self {
            summary_declared: op.summary.is_some(),
            ..Self::default()
        }
    }

    /// No value, no envelope, nothing malformed: silence (O5).
    #[must_use]
    pub fn is_silent(&self) -> bool {
        self.repliers.is_empty() && self.refusals.is_empty() && self.malformed.is_empty()
    }

    /// Every value, across repliers.
    pub fn values(&self) -> impl Iterator<Item = &V> {
        self.repliers.iter().flat_map(|r| r.values.iter())
    }

    /// The repliers whose answer may be partial: with a declared summary,
    /// those that did not end with exactly one (O6). Without one, a
    /// replier's completion cannot be told, and none is listed.
    #[must_use]
    pub fn partial(&self) -> Vec<&Replier<V, S>> {
        if !self.summary_declared {
            return Vec::new();
        }
        self.repliers
            .iter()
            .filter(|r| r.summary().is_none())
            .collect()
    }

    /// Every value and summary decoded or replaced; the rest unchanged.
    pub fn try_map<V2, S2, E>(
        self,
        mut value: impl FnMut(V) -> std::result::Result<V2, E>,
        mut summary: impl FnMut(S) -> std::result::Result<S2, E>,
    ) -> std::result::Result<Replies<V2, S2>, E> {
        let mut repliers = Vec::with_capacity(self.repliers.len());
        for r in self.repliers {
            repliers.push(Replier {
                addr: r.addr,
                key: r.key,
                params: r.params,
                values: r
                    .values
                    .into_iter()
                    .map(&mut value)
                    .collect::<std::result::Result<_, _>>()?,
                summaries: r
                    .summaries
                    .into_iter()
                    .map(&mut summary)
                    .collect::<std::result::Result<_, _>>()?,
            });
        }
        Ok(Replies {
            summary_declared: self.summary_declared,
            repliers,
            refusals: self.refusals,
            malformed: self.malformed,
            transport: self.transport,
            discarded: self.discarded,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::{CallInfo, CallMetadata, OpError, Sink};
    use crate::codec::{Json, Nothing};
    use zenkey_model::template::Bindings;

    #[test]
    fn call_metadata_is_two_optional_strings() {
        let m = CallMetadata::new("op@ws-01", "r-1");
        assert_eq!(CallMetadata::from_bytes(&m.to_bytes()), Some(m));
        assert_eq!(
            CallMetadata::from_bytes(br#"{"actor": "a", "other": 1}"#),
            Some(CallMetadata {
                actor: Some("a".into()),
                request_id: None
            })
        );
        for bad in [&b"[]"[..], br#"{"actor": 3}"#, b"not json"] {
            assert_eq!(CallMetadata::from_bytes(bad), None);
        }
    }

    #[test]
    fn a_handler_is_driven_without_a_bus() {
        let info = CallInfo::new([("if".to_owned(), vec!["eth0".to_owned()])].into(), None);
        assert_eq!(info.value("if"), Some("eth0"));
        assert!(info.is_concrete());
        let (sink, got) = Sink::<u32, ()>::memory();
        let run = async {
            sink.send(1).await.unwrap();
            sink.summary(()).await.unwrap();
            assert!(sink.send(2).await.is_err(), "the summary ends the call");
        };
        futures_lite_block_on(run);
        assert_eq!(got.lock().unwrap().values, [1]);
        let e = OpError::app_as::<Json<serde_json::Value>>("x", &serde_json::json!({"k": 1}));
        assert_eq!(e.code(), "app");
        let _ = Sink::<u32, ()>::new::<Json<u32>, Nothing>;
    }

    /// Spec §5.2 (0.7, F-65): `app` without a detail.
    #[test]
    fn app_without_a_detail() {
        let e = OpError::app_without_detail("plan rejected");
        assert_eq!((e.code(), e.envelope().detail.as_ref()), ("app", None));
    }

    /// Spec §5.1 "Over a template" (0.7, O-1, C-2): a template-wide
    /// handler names the member a fan-out answers for, through any clone,
    /// and the member must agree with what the key bound.
    #[test]
    fn a_handler_names_the_member_of_a_fan_out() {
        let b = |pairs: &[(&str, &str)]| -> Bindings {
            pairs
                .iter()
                .map(|(k, v)| ((*k).to_owned(), vec![(*v).to_owned()]))
                .collect()
        };
        let info = CallInfo::fan_out(b(&[("ns", "lab")]), None);
        let probe = info.clone();
        assert!(!info.is_concrete());
        assert_eq!(info.values(), None, "no member yet");
        assert_eq!(info.bound(), &b(&[("ns", "lab")]));
        assert!(
            info.member(&b(&[("ns", "prod"), ("if", "eth0")])).is_err(),
            "the key bound ns = lab"
        );
        info.member(&b(&[("ns", "lab"), ("if", "eth0")])).unwrap();
        assert_eq!(probe.value("if"), Some("eth0"), "clones share the member");
        info.member(&b(&[("ns", "lab"), ("if", "eth0")])).unwrap();
        assert!(
            info.member(&b(&[("ns", "lab"), ("if", "eth1")])).is_err(),
            "one member per call"
        );
        // A concrete call answers for its own member.
        let concrete = CallInfo::new(b(&[("if", "eth0")]), None);
        assert!(concrete.member(&b(&[("if", "eth1")])).is_err());
        concrete.member(&b(&[("if", "eth0")])).unwrap();
    }

    /// A minimal executor for futures that never wait on anything.
    fn futures_lite_block_on<F: std::future::Future>(f: F) -> F::Output {
        use std::task::{Context, Poll, Waker};
        let mut f = std::pin::pin!(f);
        let mut cx = Context::from_waker(Waker::noop());
        loop {
            if let Poll::Ready(v) = f.as_mut().poll(&mut cx) {
                return v;
            }
        }
    }
}
