//! The zk2 runtime: the session half of zk2 (#610 onward).
//!
//! Everything that needs no session (keys, contracts, bundles, the
//! descriptor check, the error envelope) is `zenkey-model`'s, re-exported
//! here as [`model`]. This crate adds what a Zenoh session does with them,
//! rule by rule from the spec (`spec/core.md`):
//!
//! | Module | Spec |
//! |---|---|
//! | [`config`]: what a deployment configures | §1.5, §3.2 R1–R2, §8.1 (the tokenless set) |
//! | [`service`]: bring-up, the descriptor, tokens, epochs, members | §1.5, §3.3, §8.1–§8.2 |
//! | [`presence`]: reading tokens and descriptors | §8.1 |
//! | [`retrieval`]: fetching a contract bundle | §8.4 |
//! | [`writer`]: the contract's QoS and `Encoding` on every sample; events | §2.4–§2.6, §7.2 |
//! | [`qos`]: the contract's QoS as zenoh spells it | §2.4 |
//! | [`consumer`]: data through a role's bindings | §3.2 R1–R7 |
//! | [`operation`]: serving calls; [`client`]: calling them, one address or a fleet; [`ownership`]: the split-brain diagnosis | §5.1 O1–O7, §5.2, §6 |
//! | [`call`]: what a handler receives and a caller gets back, without a session | §5.1 O3, O5–O7, §5.2 |
//! | [`shm`]: the memlock limit SHM falls back under | §7.4 |
//! | [`state`]: stamped mutations, tombstones, clocks, the owner-only GET | §4.1–§4.3, S1–S4, S6–S7 |
//! | [`archive`]: last-known state, recorded and aligned; the explicit read | §4.4, S5–S6 |
//! | [`codec`]: a Rust type and how it is carried; [`typed`]: the handles generated code is written against (#611) | §7.2 |
//!
//! **Zenoh stays reachable.** The runtime never owns the session: a
//! service holds a clone, every key is available as a key expression, and
//! raw resources are plain zenoh publishers and queryables declared with the
//! contract's QoS. The typed layers (streams #619, state #620, operations
//! #621, codegen #611) are built on these.
//!
//! **The `zenoh` feature** (default) is everything that holds a session.
//! Without it, this crate is the model, [`config`], [`Implementation`],
//! [`call`] and [`codec`]: what a contract crate generated by `zenkey-build`
//! needs for its types and its `Handlers`/`Api` traits, with no zenoh
//! dependency beyond `zenoh-keyexpr` (#611).

#[cfg(feature = "zenoh")]
pub mod archive;
pub mod call;
#[cfg(feature = "zenoh")]
pub mod client;
pub mod codec;
pub mod config;
#[cfg(feature = "zenoh")]
pub mod consumer;
#[cfg(feature = "zenoh")]
mod descriptor;
pub mod error;
pub mod implementation;
#[cfg(feature = "zenoh")]
pub mod operation;
#[cfg(feature = "zenoh")]
pub mod ownership;
#[cfg(feature = "zenoh")]
pub mod presence;
#[cfg(feature = "zenoh")]
pub mod qos;
#[cfg(feature = "zenoh")]
pub mod retrieval;
#[cfg(feature = "zenoh")]
pub mod service;
#[cfg(feature = "zenoh")]
pub mod shm;
#[cfg(feature = "zenoh")]
pub mod state;
#[cfg(feature = "zenoh")]
pub mod typed;
#[cfg(feature = "zenoh")]
pub mod writer;

/// The prost the [`codec::Protobuf`] codec is built on: generated message
/// types derive through it, so their `prost` is always this one.
pub use prost;
/// The well-known protobuf types, for generated code (`google.protobuf.*`).
pub use prost_types;
pub use zenkey_model as model;
/// The zenoh this runtime is built on: zenoh stays reachable, and generated
/// code names its session through it.
#[cfg(feature = "zenoh")]
pub use zenoh;

pub use call::{CallInfo, CallMetadata, OpError, Sink};
#[cfg(feature = "zenoh")]
pub use client::{Arrival, Client, Fleet, Outcome, Present, ReplyKind};
pub use config::{Binding, ServiceConfig};
pub use error::{Error, Result};
pub use implementation::Implementation;
#[cfg(feature = "zenoh")]
pub use operation::Call;
#[cfg(feature = "zenoh")]
pub use service::{Service, ServiceBuilder};
