//! Typed handles (#611): thin generic wrappers over the runtime's writers,
//! consumers, clients and operation servers, each taking a [`Codec`].
//!
//! Code generated by `zenkey-build` is written against these, so it stays
//! small and the encoding lives in one place ([`crate::codec`]). Every
//! handle checks at declaration that its codec carries the kind of type the
//! contract declares, and takes QoS and `Encoding` from the contract
//! through the untyped handle it wraps; nothing is configurable per call.
//!
//! | Untyped | Typed |
//! |---|---|
//! | [`crate::writer::Writer`] (streams) | [`Writer`] |
//! | [`crate::state::StateWriter`] | [`StateWriter`] |
//! | [`crate::writer::EventWriter`] | [`EventWriter`] |
//! | [`Consumer::subscribe`], [`Consumer::get`], [`Consumer::replay`] | [`subscribe`], [`get`], [`replay`]; [`last_known`] over [`crate::archive`] |
//! | [`Client::call`], [`Client::call_many`], [`Fleet::call`] | [`call`], [`call_many`], [`fan_out`] |
//! | [`ServiceBuilder::serve`] | [`serve_one`], [`serve_many`] |
//!
//! Zenoh stays reachable: every typed handle hands out the untyped one
//! (`inner()`), and every typed delivery keeps its sample.

use std::future::Future;
use std::marker::PhantomData;
use std::sync::Arc;
use std::time::{Duration, SystemTime};

use serde_json::Value;
use zenkey_model::authoring::Encoding as WireEncoding;
use zenkey_model::contract::{Body, Data, Operation, Replies as RepliesKind, Resource};
use zenkey_model::grammar::{Addr, IfaceId, KindToken, data_key};
use zenkey_model::schema::TypeId;
use zenkey_model::template::Bindings;
use zenoh::sample::Sample;
use zenoh::time::Timestamp;

use crate::call::{BoxFuture, CallInfo, OpError, Outcome, Replies, ReplyOut, Sink};
use crate::client::{Answer, Client, Fleet};
use crate::codec::{Codec, Nothing, wire_of};
use crate::consumer::{Consumer, Delivery, Subscription};
use crate::error::{Error, Result};
use crate::operation::{Call, OperationServer};
use crate::service::{ImplState, Service, ServiceBuilder};

fn kind_check<C: Codec>(ty: Option<&TypeId>, what: &str) -> Result<()> {
    if C::KIND.carries(ty) {
        Ok(())
    } else {
        Err(Error::Contract(format!(
            "{what}: the codec carries {:?}, and the contract declares {}",
            C::KIND,
            ty.map_or("no type", TypeId::kind_str)
        )))
    }
}

fn data_of(r: &Resource) -> Result<&Data> {
    match &r.body {
        Body::Data(d) => Ok(d),
        Body::Operation(_) => Err(Error::Contract(format!(
            "{}/{} is an operation",
            r.token, r.template
        ))),
    }
}

fn op_of(r: &Resource) -> Result<&Operation> {
    match &r.body {
        Body::Operation(o) => Ok(o),
        Body::Data(_) => Err(Error::Contract(format!(
            "{}/{} is not an operation",
            r.token, r.template
        ))),
    }
}

fn resource_in(impls: &[ImplState], iface: &IfaceId, resource: &str) -> Result<Resource> {
    impls
        .iter()
        .find(|s| s.imp.iface() == iface)
        .ok_or_else(|| Error::NotImplemented(iface.clone()))?
        .imp
        .resource(resource)
        .cloned()
}

/// A sample's payload, decoded by its `Encoding`, else the contract's.
fn decode_sample<C: Codec>(
    sample: &Sample,
    contract: Option<WireEncoding>,
) -> std::result::Result<C::Value, String> {
    let enc = sample.encoding().to_string();
    C::decode(&sample.payload().to_bytes(), wire_of(Some(&enc), contract))
}

/// Checks the codecs of a data resource's type and attachment.
fn check_data<C: Codec, A: Codec>(r: &Resource) -> Result<&Data> {
    let d = data_of(r)?;
    let at = format!("{}/{}", r.token, r.template);
    kind_check::<C>(Some(&d.type_), &format!("{at} type"))?;
    kind_check::<A>(d.attachment.as_ref(), &format!("{at} attachment"))?;
    Ok(d)
}

/// A stream member's writer, typed (§2.4, §7.2): `C` the type, `A` the
/// declared attachment ([`Nothing`] when there is none).
pub struct Writer<C, A = Nothing> {
    inner: crate::writer::Writer,
    wire: Option<WireEncoding>,
    attachment_wire: Option<WireEncoding>,
    _codec: PhantomData<fn() -> (C, A)>,
}

impl<C: Codec, A: Codec> Writer<C, A> {
    /// Wraps a writer of `r`, checking the codecs against it.
    pub fn new(inner: crate::writer::Writer, r: &Resource) -> Result<Self> {
        let d = check_data::<C, A>(r)?;
        Ok(Self {
            inner,
            wire: d.encoding,
            attachment_wire: d.attachment_encoding,
            _codec: PhantomData,
        })
    }

    /// Declares the writer on the builder ([`ServiceBuilder::declare_writer`]).
    pub async fn declare(
        b: &mut ServiceBuilder,
        iface: &IfaceId,
        resource: &str,
        values: &Bindings,
    ) -> Result<Self> {
        let r = resource_in(b.impls(), iface, resource)?;
        check_data::<C, A>(&r)?;
        let w = b.declare_writer(iface, resource, values).await?;
        Self::new(w, &r)
    }

    /// A writer on a member of a resource exposed before start
    /// ([`Service::writer`]).
    pub async fn on(
        svc: &Service,
        iface: &IfaceId,
        resource: &str,
        values: &Bindings,
    ) -> Result<Self> {
        let r = resource_in(svc.impls(), iface, resource)?;
        check_data::<C, A>(&r)?;
        let w = svc.writer(iface, resource, values).await?;
        Self::new(w, &r)
    }

    /// Puts a value. It is encoded before the future starts, so the value
    /// need not outlive the call.
    pub fn put(&self, value: &C::Value) -> impl Future<Output = Result<()>> + Send + use<'_, C, A> {
        let bytes = C::encode(value, self.wire).map_err(Error::Payload);
        async move { self.inner.put(bytes?).await }
    }

    /// Puts a value with its declared attachment (§2.3).
    pub fn put_with(
        &self,
        value: &C::Value,
        attachment: &A::Value,
    ) -> impl Future<Output = Result<()>> + Send + use<'_, C, A> {
        let bytes = C::encode(value, self.wire)
            .and_then(|v| Ok((v, A::encode(attachment, self.attachment_wire)?)))
            .map_err(Error::Payload);
        async move {
            let (v, a) = bytes?;
            self.inner.put_with(v, Some(a)).await
        }
    }

    /// The untyped writer: for a zero-copy payload (SHM, §7.4) or zenoh.
    #[must_use]
    pub fn inner(&self) -> &crate::writer::Writer {
        &self.inner
    }
}

/// A state member's writer, typed: stamped puts and deletes (S1).
pub struct StateWriter<C> {
    inner: crate::state::StateWriter,
    wire: Option<WireEncoding>,
    _codec: PhantomData<fn() -> C>,
}

impl<C: Codec> StateWriter<C> {
    /// Wraps a state writer of `r`, checking the codec against it.
    pub fn new(inner: crate::state::StateWriter, r: &Resource) -> Result<Self> {
        let d = check_data::<C, Nothing>(r)?;
        Ok(Self {
            inner,
            wire: d.encoding,
            _codec: PhantomData,
        })
    }

    /// Declares the writer on the builder
    /// ([`ServiceBuilder::declare_state_writer`]).
    pub async fn declare(
        b: &mut ServiceBuilder,
        iface: &IfaceId,
        resource: &str,
        values: &Bindings,
    ) -> Result<Self> {
        let r = resource_in(b.impls(), iface, resource)?;
        check_data::<C, Nothing>(&r)?;
        let w = b.declare_state_writer(iface, resource, values).await?;
        Self::new(w, &r)
    }

    /// A writer on a member of a state resource exposed before start
    /// ([`Service::state_writer`]).
    pub async fn on(
        svc: &mut Service,
        iface: &IfaceId,
        resource: &str,
        values: &Bindings,
    ) -> Result<Self> {
        let r = resource_in(svc.impls(), iface, resource)?;
        check_data::<C, Nothing>(&r)?;
        let w = svc.state_writer(iface, resource, values).await?;
        Self::new(w, &r)
    }

    /// Puts a value, stamped; returns the stamp.
    pub fn put(
        &self,
        value: &C::Value,
    ) -> impl Future<Output = Result<Timestamp>> + Send + use<'_, C> {
        let bytes = C::encode(value, self.wire).map_err(Error::Payload);
        async move { self.inner.put(bytes?).await }
    }

    /// Deletes the member, stamped (S3).
    pub async fn delete(&self) -> Result<Timestamp> {
        self.inner.delete().await
    }

    /// The untyped writer.
    #[must_use]
    pub fn inner(&self) -> &crate::state::StateWriter {
        &self.inner
    }
}

/// An event's writer, typed: one key per occurrence (§2.6).
pub struct EventWriter<C> {
    inner: crate::writer::EventWriter,
    wire: Option<WireEncoding>,
    _codec: PhantomData<fn() -> C>,
}

impl<C: Codec> EventWriter<C> {
    /// Wraps an event writer of `r`, checking the codec against it.
    pub fn new(inner: crate::writer::EventWriter, r: &Resource) -> Result<Self> {
        let d = check_data::<C, Nothing>(r)?;
        Ok(Self {
            inner,
            wire: d.encoding,
            _codec: PhantomData,
        })
    }

    /// Declares the writer on the builder ([`ServiceBuilder::event_writer`]).
    pub fn declare(
        b: &mut ServiceBuilder,
        iface: &IfaceId,
        resource: &str,
        values: &Bindings,
    ) -> Result<Self> {
        let r = resource_in(b.impls(), iface, resource)?;
        check_data::<C, Nothing>(&r)?;
        let w = b.event_writer(iface, resource, values)?;
        Self::new(w, &r)
    }

    /// A writer on a member of an event exposed before start.
    pub fn on(svc: &Service, iface: &IfaceId, resource: &str, values: &Bindings) -> Result<Self> {
        let r = resource_in(svc.impls(), iface, resource)?;
        check_data::<C, Nothing>(&r)?;
        let w = svc.event_writer(iface, resource, values)?;
        Self::new(w, &r)
    }

    /// Publishes one occurrence now; returns its key.
    pub fn put(
        &self,
        value: &C::Value,
    ) -> impl Future<Output = Result<String>> + Send + use<'_, C> {
        let bytes = C::encode(value, self.wire).map_err(Error::Payload);
        async move { self.inner.put(bytes?).await }
    }

    /// Publishes one occurrence observed at `at`.
    pub fn put_at(
        &self,
        value: &C::Value,
        at: SystemTime,
    ) -> impl Future<Output = Result<String>> + Send + use<'_, C> {
        let bytes = C::encode(value, self.wire).map_err(Error::Payload);
        async move { self.inner.put_at(bytes?, at).await }
    }

    /// The untyped writer.
    #[must_use]
    pub fn inner(&self) -> &crate::writer::EventWriter {
        &self.inner
    }
}

/// One delivered sample, decoded and attributed. A payload that does not
/// decode as the declared type is delivered as such, with the reason:
/// neither garbage nor nothing (§7.1).
#[derive(Debug, Clone)]
pub struct Received<T> {
    /// The provider whose key carried it.
    pub provider: Addr,
    /// `<kind token>/<template>`.
    pub resource: String,
    /// The template's parameters, unslugged.
    pub values: Bindings,
    pub value: std::result::Result<T, String>,
    pub sample: Sample,
}

fn received<C: Codec>(d: Delivery, wire: Option<WireEncoding>) -> Received<C::Value> {
    Received {
        value: decode_sample::<C>(&d.sample, wire),
        provider: d.provider,
        resource: d.resource,
        values: d.values,
        sample: d.sample,
    }
}

fn consumer_data<C: Codec>(consumer: &Consumer, resource: &str) -> Result<Option<WireEncoding>> {
    // A declared attachment is the subscriber's to read from the sample.
    let r = consumer.resource(resource)?;
    let d = data_of(r)?;
    kind_check::<C>(Some(&d.type_), resource)?;
    Ok(d.encoding)
}

/// Subscribes to `resource` through the role ([`Consumer::subscribe`]),
/// decoding every sample as `C`.
pub async fn subscribe<C, F>(
    consumer: &Consumer,
    resource: &str,
    callback: F,
) -> Result<Subscription>
where
    C: Codec,
    F: Fn(Received<C::Value>) + Send + Sync + 'static,
{
    let wire = consumer_data::<C>(consumer, resource)?;
    consumer
        .subscribe(resource, move |d: Delivery| {
            callback(received::<C>(d, wire))
        })
        .await
}

/// Replays an event's occurrences within `retention` ([`Consumer::replay`]).
pub async fn replay<C: Codec>(
    consumer: &Consumer,
    resource: &str,
    retention: Duration,
    timeout: Duration,
) -> Result<Vec<Received<C::Value>>> {
    let wire = consumer_data::<C>(consumer, resource)?;
    Ok(consumer
        .replay(resource, retention, timeout)
        .await?
        .into_iter()
        .map(|d| received::<C>(d, wire))
        .collect())
}

/// One key of an owner's answer, decoded (S6).
#[derive(Debug, Clone)]
pub enum Current<T> {
    /// The key's value, as the owner holds it now.
    Value {
        key: String,
        value: std::result::Result<T, String>,
        sample: Box<Sample>,
    },
    /// Deleted within the window, with the deletion's stamp.
    Deleted {
        key: String,
        timestamp: Option<Timestamp>,
    },
}

impl<T> Current<T> {
    #[must_use]
    pub fn key(&self) -> &str {
        match self {
            Self::Value { key, .. } | Self::Deleted { key, .. } => key,
        }
    }

    #[must_use]
    pub fn timestamp(&self) -> Option<Timestamp> {
        match self {
            Self::Value { sample, .. } => sample.timestamp().copied(),
            Self::Deleted { timestamp, .. } => *timestamp,
        }
    }
}

/// What a typed state GET to the owner found (S4, S6).
#[derive(Debug, Clone)]
pub enum StateGet<T> {
    /// The owner answered: current state, key by key.
    Answered(Vec<Current<T>>),
    /// No reply within the timeout: never a verdict (O5). An archive's
    /// answer is last-known ([`last_known`]).
    Silent,
}

/// GETs current state from its owners ([`Consumer::get`]), decoded as `C`.
pub async fn get<C: Codec>(
    consumer: &Consumer,
    resource: &str,
    values: Option<&Bindings>,
    timeout: Duration,
) -> Result<StateGet<C::Value>> {
    let wire = consumer_data::<C>(consumer, resource)?;
    Ok(match consumer.get(resource, values, timeout).await? {
        crate::state::StateGet::Silent => StateGet::Silent,
        crate::state::StateGet::Answered(v) => StateGet::Answered(
            v.into_iter()
                .map(|c| match c {
                    crate::state::Current::Value { key, sample } => Current::Value {
                        key,
                        value: decode_sample::<C>(&sample, wire),
                        sample,
                    },
                    crate::state::Current::Deleted { key, timestamp } => {
                        Current::Deleted { key, timestamp }
                    }
                })
                .collect(),
        ),
    })
}

/// A key's last-known state from an archive (S5), decoded. Never current
/// (S6).
#[derive(Debug, Clone)]
pub struct LastKnown<T> {
    /// The owner's key it records.
    pub origin: String,
    /// The value, or `None` for a tombstone.
    pub value: Option<std::result::Result<T, String>>,
    pub timestamp: Option<Timestamp>,
    /// `{"iface", "contract", "type"}`: the value's type identity (§7.1).
    pub identity: Value,
    /// `false` while alignment has not confirmed the key.
    pub confirmed: bool,
}

/// Reads one member of a state resource of `provider` from the archive at
/// `archive`, explicitly (S5, [`crate::archive::last_known`]). `values` binds
/// the template's parameters, over the role's bindings (R2).
pub async fn last_known<C: Codec>(
    consumer: &Consumer,
    archive: &Addr,
    provider: &Addr,
    resource: &str,
    values: &Bindings,
    timeout: Duration,
) -> Result<Option<LastKnown<C::Value>>> {
    let wire = consumer_data::<C>(consumer, resource)?;
    let r = consumer.resource(resource)?;
    if !matches!(r.token, KindToken::State | KindToken::ExplicitState) {
        return Err(Error::Contract(format!("{resource:?} is not state")));
    }
    let mut merged: Bindings = consumer
        .params()
        .iter()
        .map(|(k, v)| (k.clone(), vec![v.clone()]))
        .collect();
    merged.extend(values.clone());
    let chunks = r
        .template
        .build(&merged)
        .map_err(|e| Error::Contract(format!("{resource:?}: {e}")))?;
    let refs: Vec<&str> = chunks.iter().map(String::as_str).collect();
    let origin = data_key(provider, consumer.interface(), r.token, &refs)?.to_string();
    let found = crate::archive::last_known(consumer.session(), archive, &origin, timeout).await?;
    Ok(found.map(|l| {
        let enc = l.encoding.as_ref().map(ToString::to_string);
        LastKnown {
            value: l
                .value
                .map(|b| C::decode(&b, wire_of(enc.as_deref(), wire))),
            origin: l.origin,
            timestamp: l.timestamp,
            identity: l.identity,
            confirmed: l.confirmed,
        }
    }))
}

fn op_check<Req: Codec, Resp: Codec, Sum: Codec>(op: &Operation, at: &str) -> Result<()> {
    kind_check::<Req>(Some(&op.request), &format!("{at} request"))?;
    kind_check::<Resp>(Some(&op.response), &format!("{at} response"))?;
    kind_check::<Sum>(op.summary.as_ref(), &format!("{at} summary"))
}

fn decode_answer<C: Codec>(a: &Answer, wire: Option<WireEncoding>) -> Result<C::Value> {
    decode_sample::<C>(&a.sample, wire).map_err(|e| {
        Error::Payload(format!(
            "the reply on {} does not decode as its declared type: {e}",
            a.key()
        ))
    })
}

fn typed_replies<Resp: Codec, Sum: Codec>(
    out: crate::client::Replies,
    wire: Option<WireEncoding>,
) -> Result<Replies<Resp::Value, Sum::Value>> {
    out.try_map(
        |a| decode_answer::<Resp>(&a, wire),
        |a| decode_answer::<Sum>(&a, wire),
    )
}

/// Calls a one-reply operation at `addr` ([`Client::call`]), the request
/// encoded as `Req` and the value reply decoded as `Resp`. A value reply that
/// does not decode is the replier's bug: [`Error::Payload`], never silence.
pub async fn call<Req: Codec, Resp: Codec>(
    client: &Client,
    addr: &Addr,
    resource: &str,
    values: &Bindings,
    request: Req::Value,
) -> Result<Outcome<Resp::Value>> {
    let (_, op) = client.op(resource)?;
    op_check::<Req, Resp, Nothing>(&op, resource)?;
    let bytes = Req::encode(&request, op.encoding).map_err(Error::Payload)?;
    client
        .call(addr, resource, values, bytes)
        .await?
        .try_map(|a| decode_answer::<Resp>(&a, op.encoding))
}

/// Calls a many-reply operation at `addr` ([`Client::call_many`]): every
/// value decoded as `Resp`, every summary as `Sum` (O6).
pub async fn call_many<Req: Codec, Resp: Codec, Sum: Codec>(
    client: &Client,
    addr: &Addr,
    resource: &str,
    values: &Bindings,
    request: Req::Value,
) -> Result<Replies<Resp::Value, Sum::Value>> {
    let (_, op) = client.op(resource)?;
    op_check::<Req, Resp, Sum>(&op, resource)?;
    let bytes = Req::encode(&request, op.encoding).map_err(Error::Payload)?;
    typed_replies::<Resp, Sum>(
        client.call_many(addr, resource, values, bytes).await?,
        op.encoding,
    )
}

/// Fans a call out ([`Fleet::call`], O2): only to a `fanout = "allowed"`
/// operation; every reply decoded and attributed.
pub async fn fan_out<Req: Codec, Resp: Codec, Sum: Codec>(
    fleet: &Fleet,
    resource: &str,
    values: &Bindings,
    request: Req::Value,
) -> Result<Replies<Resp::Value, Sum::Value>> {
    let (_, op) = fleet.op(resource)?;
    op_check::<Req, Resp, Sum>(&op, resource)?;
    let bytes = Req::encode(&request, op.encoding).map_err(Error::Payload)?;
    typed_replies::<Resp, Sum>(fleet.call(resource, values, bytes).await?, op.encoding)
}

fn decode_request<C: Codec>(
    call: &Call,
    wire: Option<WireEncoding>,
) -> std::result::Result<C::Value, OpError> {
    let bytes = call
        .payload()
        .map(|p| p.to_bytes().into_owned())
        .unwrap_or_default();
    let enc = call.query().encoding().map(ToString::to_string);
    C::decode(&bytes, wire_of(enc.as_deref(), wire))
        .map_err(|e| OpError::invalid_request(format!("the request does not decode: {e}")))
}

fn served_op<Req: Codec, Resp: Codec, Sum: Codec>(
    b: &ServiceBuilder,
    iface: &IfaceId,
    resource: &str,
    replies: RepliesKind,
) -> Result<Operation> {
    let r = resource_in(b.impls(), iface, resource)?;
    let op = op_of(&r)?.clone();
    if op.replies != replies {
        return Err(Error::Contract(format!(
            "{iface} {resource:?} is replies = {:?}",
            op.replies
        )));
    }
    op_check::<Req, Resp, Sum>(&op, resource)?;
    Ok(op)
}

/// Serves a one-reply operation over its whole template
/// ([`ServiceBuilder::serve`]): the request decoded as `Req` (a failure is
/// `invalid_request`), the handler's value encoded as `Resp` and replied, its
/// error refused with its envelope (O3).
pub async fn serve_one<Req, Resp, H, Fut>(
    b: &mut ServiceBuilder,
    iface: &IfaceId,
    resource: &str,
    handler: H,
) -> Result<OperationServer>
where
    Req: Codec,
    Resp: Codec,
    H: Fn(Req::Value, CallInfo) -> Fut + Send + Sync + 'static,
    Fut: Future<Output = std::result::Result<Resp::Value, OpError>> + Send + 'static,
{
    let op = served_op::<Req, Resp, Nothing>(b, iface, resource, RepliesKind::One)?;
    let wire = op.encoding;
    let handler = Arc::new(handler);
    b.serve(iface, resource, None, move |call: Call| {
        let h = Arc::clone(&handler);
        async move {
            let req = decode_request::<Req>(&call, wire)?;
            let resp = h(req, CallInfo::of(&call)).await?;
            let bytes = Resp::encode(&resp, wire)
                .map_err(|e| OpError::internal(format!("the response does not encode: {e}")))?;
            call.reply(bytes).await?;
            Ok(())
        }
    })
    .await
}

/// A [`Sink`]'s way onto the runtime's call.
struct CallOut(Call);

impl ReplyOut for CallOut {
    fn value(&self, bytes: Vec<u8>) -> BoxFuture<'_, Result<()>> {
        Box::pin(self.0.reply(bytes))
    }
    fn summary(&self, bytes: Vec<u8>) -> BoxFuture<'_, Result<()>> {
        Box::pin(self.0.summary(bytes))
    }
}

/// Serves a `replies = "many"` operation over its whole template: the
/// handler sends values, then the summary when one is declared, through a
/// [`Sink`] (O6). A handler that returns without the declared summary is
/// answered `internal` by the runtime.
pub async fn serve_many<Req, Resp, Sum, H, Fut>(
    b: &mut ServiceBuilder,
    iface: &IfaceId,
    resource: &str,
    handler: H,
) -> Result<OperationServer>
where
    Req: Codec,
    Resp: Codec,
    Sum: Codec,
    H: Fn(Req::Value, CallInfo, Sink<Resp::Value, Sum::Value>) -> Fut + Send + Sync + 'static,
    Fut: Future<Output = std::result::Result<(), OpError>> + Send + 'static,
{
    let op = served_op::<Req, Resp, Sum>(b, iface, resource, RepliesKind::Many)?;
    let wire = op.encoding;
    let handler = Arc::new(handler);
    b.serve(iface, resource, None, move |call: Call| {
        let h = Arc::clone(&handler);
        async move {
            let req = decode_request::<Req>(&call, wire)?;
            let sink = Sink::new::<Resp, Sum>(Arc::new(CallOut(call.clone())), wire);
            h(req, CallInfo::of(&call), sink).await
        }
    })
    .await
}
